using System.Text;
using System.Text.Encodings.Web;

namespace SilentScan.Core.Reporting;

/// <summary>
/// Renders <see cref="RuleCatalog.BaseRules"/> as the public rule-reference page
/// (<c>docs/rules.html</c>) - CLAUDE.md's standing-docs entry for it: generated by the CLI's
/// <c>rules-doc</c> verb, never hand-edited. One page section per rule: id, rationale, and (only
/// where the catalog genuinely has one - most rows don't, honestly) fix guidance and a link to a
/// real fixture file.
/// </summary>
public static class RuleCatalogHtmlWriter
{
    public static string Write()
    {
        var rules = RuleCatalog.BaseRules.OrderBy(r => r.Id, StringComparer.Ordinal).ToList();
        var withFixGuidance = rules.Count(r => r.FixGuidance is not null);
        var withExample = rules.Count(r => r.ExampleFixturePath is not null);

        var sb = new StringBuilder();
        sb.Append("""
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>SilentScan Rules</title>
            <style>
              :root {
                color-scheme: light dark;
                --bg: #ffffff;
                --fg: #1a1a1a;
                --muted: #5c5c5c;
                --accent: #0a5cff;
                --border: #e0e0e0;
                --code-bg: #f5f5f5;
              }
              @media (prefers-color-scheme: dark) {
                :root {
                  --bg: #0d1117;
                  --fg: #e6edf3;
                  --muted: #9198a1;
                  --accent: #4993ff;
                  --border: #30363d;
                  --code-bg: #161b22;
                }
              }
              * { box-sizing: border-box; }
              body {
                margin: 0;
                background: var(--bg);
                color: var(--fg);
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                line-height: 1.6;
              }
              main {
                max-width: 860px;
                margin: 0 auto;
                padding: 4rem 1.5rem 6rem;
              }
              h1 {
                font-size: 2.2rem;
                margin-bottom: 0.25rem;
              }
              .tagline {
                color: var(--muted);
                font-size: 1.1rem;
                margin-top: 0;
                margin-bottom: 2.5rem;
              }
              code, pre {
                font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
                background: var(--code-bg);
                border-radius: 6px;
              }
              code {
                padding: 0.15em 0.4em;
                font-size: 0.9em;
              }
              a { color: var(--accent); }
              .rule {
                border-top: 1px solid var(--border);
                padding: 1.5rem 0;
              }
              .rule:first-of-type { border-top: none; }
              .rule-id {
                font-size: 1rem;
                margin: 0 0 0.5rem;
              }
              .rationale { margin: 0.5rem 0; }
              .fix {
                margin: 0.5rem 0;
                padding-left: 1rem;
                border-left: 3px solid var(--accent);
              }
              .fix-label {
                font-weight: 600;
                color: var(--muted);
                font-size: 0.85rem;
                text-transform: uppercase;
                letter-spacing: 0.04em;
              }
              .example { margin: 0.5rem 0; font-size: 0.9em; color: var(--muted); }
              footer {
                margin-top: 4rem;
                color: var(--muted);
                font-size: 0.85rem;
              }
            </style>
            </head>
            <body>
            <main>
              <h1>SilentScan rules</h1>
            """);

        sb.Append("  <p class=\"tagline\">")
          .Append(rules.Count)
          .Append(" rules. ")
          .Append(withFixGuidance)
          .Append(" carry fix guidance; ")
          .Append(withExample)
          .Append(" link a real fixture. Generated from the same catalog SARIF's own <code>rules</code> block reads &mdash; never hand-edited.</p>\n\n");

        foreach (var rule in rules)
        {
            sb.Append("  <section class=\"rule\">\n");
            sb.Append("    <h3 class=\"rule-id\"><code>").Append(HtmlEncoder.Default.Encode(rule.Id)).Append("</code></h3>\n");
            sb.Append("    <p class=\"rationale\">").Append(HtmlEncoder.Default.Encode(rule.Rationale)).Append("</p>\n");
            if (rule.FixGuidance is { } fixGuidance)
            {
                sb.Append("    <p class=\"fix\"><span class=\"fix-label\">Fix</span><br>").Append(HtmlEncoder.Default.Encode(fixGuidance)).Append("</p>\n");
            }

            if (rule.ExampleFixturePath is { } examplePath)
            {
                sb.Append("    <p class=\"example\">Example: <code>").Append(HtmlEncoder.Default.Encode(examplePath)).Append("</code></p>\n");
            }

            sb.Append("  </section>\n\n");
        }

        sb.Append("""
              <footer>
                Generated by <code>silentscan rules-doc</code> from RuleCatalog - do not hand-edit.
              </footer>
            </main>
            </body>
            </html>
            """);

        return sb.ToString();
    }
}
