using System.Text;
using System.Text.Encodings.Web;

namespace SilentScan.Core.Reporting;

/// <summary>
/// Renders <see cref="RuleCatalog.BaseRules"/> as the public rule index (<c>docs/rules.html</c>) -
/// CLAUDE.md's standing-docs entry for it: generated by the CLI's <c>rules-doc</c> verb, never
/// hand-edited. Rules are grouped by family (the id's own <c>silentscan/&lt;family&gt;/...</c>
/// segment) and link out to each rule's own page at <see cref="RuleDocSite"/>'s URL
/// (<see cref="RulePageHtmlWriter"/> renders those).
/// </summary>
public static class RuleCatalogHtmlWriter
{
    public static string Write()
    {
        var rules = RuleCatalog.BaseRules.OrderBy(r => r.Id, StringComparer.Ordinal).ToList();
        var withFixGuidance = rules.Count(r => r.FixGuidance is not null);
        var withExamples = rules.Count(r => r.Examples.Count > 0);
        var families = rules.GroupBy(Family).OrderBy(g => g.Key, StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.Append("""
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>SilentScan Rules</title>
            <style>
            """);
        sb.Append(RuleDocStyle.Css).Append("\n</style>\n</head>\n<body>\n<main>\n  <h1>SilentScan rules</h1>\n");

        sb.Append("  <p class=\"tagline\">")
          .Append(rules.Count)
          .Append(" rules. ")
          .Append(withFixGuidance)
          .Append(" carry fix guidance; ")
          .Append(withExamples)
          .Append(" link a real fixture example. Generated from the same catalog SARIF's own <code>rules</code> block reads &mdash; never hand-edited.</p>\n\n");

        foreach (var family in families)
        {
            sb.Append("  <section class=\"family-section\">\n");
            sb.Append("    <h2>").Append(HtmlEncoder.Default.Encode(family.Key)).Append("</h2>\n");
            sb.Append("    <ul class=\"rule-list\">\n");
            foreach (var rule in family)
            {
                var url = RuleDocSite.RelativePath(rule.Id);
                var title = RuleDocSite.HumanizeTitle(rule.Id);
                sb.Append("      <li><a class=\"id\" href=\"").Append(HtmlEncoder.Default.Encode(url)).Append("\">")
                  .Append(HtmlEncoder.Default.Encode(title)).Append("</a> <code class=\"rule-key\">")
                  .Append(HtmlEncoder.Default.Encode(rule.Id)).Append("</code><span class=\"snippet\">")
                  .Append(HtmlEncoder.Default.Encode(FirstSentence(rule.Rationale))).Append("</span></li>\n");
            }

            sb.Append("    </ul>\n");
            sb.Append("  </section>\n\n");
        }

        sb.Append("""
              <footer>
                Generated by <code>silentscan rules-doc</code> from RuleCatalog - do not hand-edit.
              </footer>
            </main>
            </body>
            </html>
            """);

        return sb.ToString();
    }

    /// <summary>The id's own <c>silentscan/&lt;family&gt;/...</c> segment - the grouping this index is organized by.</summary>
    private static string Family(RuleDefinition rule)
    {
        var parts = rule.Id.Split('/');
        return parts.Length >= 2 ? parts[1] : rule.Id;
    }

    private static string FirstSentence(string rationale)
    {
        var dashIndex = rationale.IndexOf(" - ", StringComparison.Ordinal);
        var periodIndex = rationale.IndexOf(". ", StringComparison.Ordinal);
        var cut = new[] { dashIndex, periodIndex }.Where(i => i >= 0).DefaultIfEmpty(-1).Min();
        return cut >= 0 ? rationale[..cut].TrimEnd('.') + "." : rationale;
    }
}
