using SilentScan.Core.Reporting.RuleHarness.Adapters;

namespace SilentScan.Core.Reporting.RuleHarness;

public static class RuleRegistry
{
    public static IReadOnlyList<IRule> All { get; } =
    [
        new WaitForRule(),
        new CursorCloseOnCommitRule(),
        new CompositeIndexLeadingColumnRule(),
        new MissingStatisticsRule(),
        new SessionDateSettingRule(),
        new CartesianJoinRule(),
        new TruncateSwallowedRule(),
        new CatchAllPredicateRule(),
        new BareTopNoOrderByRule(),
        new StringConcatNullRule(),
        new AggregateDivisionColumnstoreRule(),
        new ParameterReassignmentPredicateRule(),
        new NotInNullableSubqueryRule(),
        new NonUniqueUpdateSourceRule(),
        new FloatEqualityPredicateRule(),
        new FloatOrderDependentAggregateRule(),
        new AlwaysEncryptedOrderByRule(),
        new OperandComparabilityRule(),
        new IndexCoverageRule(),
        new SelfReferencingDmlRule(),
        new TransactionHygieneRule(),
        new DynamicDataMaskingRule(),

        new ModuleCompileFlagRule(),
        new WindowFrameRule(),
        new WindowFunctionArgumentRule(),
        new StringSplitArgumentRule(),
        new ViewOrderingRule(),
        new IndexHintRule(),
        new CodeMetricRule(),
        new FormattingRule(),
        new NamingRule(),
        new DeadCodeRule(),
        new DuplicationRule(),
        new DeprecatedSyntaxRule(),
        new ControlFlowRiskRule(),
        new QueryAntiPatternRule(),
        new TriggerCorrectnessRule(),
        new ForcedSerialRule(),
        new SetOptionRule(),

        new PartialCompositeForeignKeyJoinRule(),
        new TryCastComputedColumnPredicateRule(),
        new StatementShapeRule(),
        new MultiReferencedCteRule(),
        new PostExpansionJoinWidthRule(),
        new SelectStarViewRule(),
        new OutputParameterRule(),
        new UnindexedTempTableUsageRule(),

        new ColumnCollationDriftRule(),
        new AnsiPaddingOffColumnRule(),
        new CrossTableTypeDriftRule(),
        new TriggerOrderRule(),
        new ProcCallArgumentMismatchRule(),
        new ProcCallTableValuedArgumentMismatchRule(),
        new SpExecuteSqlParameterMismatchRule(),
        new MaxTypedColumnRule(),
        new ColumnstoreUnsupportedColumnTypeRule(),
        new SelectiveXmlIndexValueColumnRule(),
        new MemoryOptimizedUnsupportedColumnTypeRule(),
        new MemoryOptimizedUnsupportedIndexOptionRule(),
        new AlwaysEncryptedKeyColumnRule(),
        new AlterColumnSafetyRule(),
        new MemoryOptimizedForeignKeyRule(),
        new MemoryOptimizedSchemaOnlyDurabilityRule(),
        new NonPersistedComputedColumnRule(),
        new UntrustedConstraintRule(),
        new CheckConstraintRule(),
        new SecurityPredicateIndexRule(),
        new DefaultNullableConstraintRule(),
        new CascadingForeignKeyRule(),
        new TemporalTableHistoryIndexGapRule(),
        new NestedViewDepthRule(),

        new CrossModuleLockOrderRule(),
        new TriggerRecursionCycleRule(),

        new TvfFenceRule(),
        new ScalarUdfRule(),
        new SecurityRule(),
    ];
}
