<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>silentscan</AssemblyName>
    <RootNamespace>SilentScan.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <ProjectReference Include="../SilentScan.Core/SilentScan.Core.csproj" />
    <ProjectReference Include="../SilentScan.Live/SilentScan.Live.csproj" />
    <ProjectReference Include="../SilentScan.NoCommentsAnalyzer/SilentScan.NoCommentsAnalyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SilentScan.Tests" />
  </ItemGroup>

</Project>
