using System.CommandLine;
using System.Text.Json;
using System.Text.Json.Serialization;
using SilentScan.Core.TypeInference;
using SilentScan.Verify.Oracle;

namespace SilentScan.Verify.Commands;

public sealed record TypeMatrixFamilies(
    IReadOnlyList<(SqlTypeCategory Category, string Syntax)>? NumericFamily = null,
    IReadOnlyList<(SqlTypeCategory Category, string Syntax)>? DateTimeFamily = null,
    IReadOnlyList<(SqlTypeCategory Category, string Syntax)>? StringFamily = null,
    IReadOnlyList<string>? Collations = null,
    IReadOnlyList<(SqlTypeCategory Category, string Syntax)>? CrossFamilyOther = null,
    IReadOnlyList<(SqlTypeCategory Category, string Syntax)>? BinaryFamily = null);

public static class GenerateTypeMatrixCommand
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        Converters = { new JsonStringEnumConverter() },
    };

    public static Command Create()
    {
        var outputOption = new Option<string>("--output")
        {
            Description = "Path to write the matrix JSON to.",
            DefaultValueFactory = _ => "src/SilentScan.Core/Rules/TypePairMatrix.json",
        };

        var command = new Command("generate-type-matrix", "Probe the Docker SQL Server oracle for every numeric/datetime/string type-pair cell and write the checked-in matrix JSON.");
        command.Options.Add(outputOption);

        command.SetAction(async (parseResult, cancellationToken) =>
        {
            var output = parseResult.GetValue(outputOption)!;
            return await RunAsync(output, SqlServerOptions.LocalDocker, Console.Out, cancellationToken: cancellationToken);
        });

        return command;
    }

    internal static async Task<int> RunAsync(
        string outputPath,
        SqlServerOptions sqlOptions,
        TextWriter stdout,
        TypeMatrixFamilies? families = null,
        CancellationToken cancellationToken = default)
    {
        families ??= new TypeMatrixFamilies();
        var generator = new TypeMatrixGenerator(sqlOptions);
        var (entries, serverVersion) = await generator.GenerateAsync(
            families.NumericFamily ?? TypeMatrixGenerator.NumericFamily,
            families.DateTimeFamily ?? TypeMatrixGenerator.DateTimeFamily,
            families.StringFamily ?? TypeMatrixGenerator.StringFamily,
            families.Collations ?? TypeMatrixGenerator.Collations,
            families.CrossFamilyOther ?? TypeMatrixGenerator.CrossFamilyOther,
            families.BinaryFamily ?? TypeMatrixGenerator.BinaryFamily,
            cancellationToken);

        var document = new
        {
            ServerVersion = serverVersion,
            ProbedAtUtc = DateTime.UtcNow.ToString("yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture),
            Notes = "Generated by SilentScan.Verify generate-type-matrix against the local Docker SQL Server, compat level 160, compile-only via SET SHOWPLAN_XML. "
                + "ColumnConverts=true means a CONVERT_IMPLICIT node targets the column (ConvertImplicitDetector). "
                + "DynamicRangeSeekAvailable=true means the plan contains an Intrinsic GetRangeThroughConvert node. "
                + "CompileFailed=true means SQL Server rejected the comparison outright (the pair is not implicitly comparable at all).",
            Entries = entries,
        };

        var json = JsonSerializer.Serialize(document, JsonOptions);
        await File.WriteAllTextAsync(outputPath, json + Environment.NewLine, cancellationToken);
        await stdout.WriteLineAsync($"Wrote {entries.Count} entries (server {serverVersion}) to {outputPath}");

        return 0;
    }
}
