using System.CommandLine;
using System.Text.Json;
using System.Text.Json.Serialization;
using SilentScan.Verify.Oracle;

namespace SilentScan.Verify.Commands;

/// <summary>
/// `silentscan-verify generate-type-matrix` — regenerates the checked-in oracle-probed
/// type-pair matrix that
/// `SilentScan.Core.Rules.TypePairMatrix` loads at runtime. Run this after upgrading the Docker
/// SQL Server image, since the matrix records empirical facts about a specific optimizer build,
/// not something derivable from the T-SQL precedence list alone.
/// </summary>
public static class GenerateTypeMatrixCommand
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        Converters = { new JsonStringEnumConverter() },
    };

    public static Command Create()
    {
        var outputOption = new Option<string>("--output")
        {
            Description = "Path to write the matrix JSON to.",
            DefaultValueFactory = _ => "src/SilentScan.Core/Rules/TypePairMatrix.json",
        };

        var command = new Command("generate-type-matrix", "Probe the Docker SQL Server oracle for every numeric/datetime/string type-pair cell and write the checked-in matrix JSON.");
        command.Options.Add(outputOption);

        command.SetAction(async (parseResult, cancellationToken) =>
        {
            var output = parseResult.GetValue(outputOption)!;
            return await RunAsync(output, SqlServerOptions.LocalDocker, Console.Out, cancellationToken);
        });

        return command;
    }

    internal static async Task<int> RunAsync(string outputPath, SqlServerOptions sqlOptions, TextWriter stdout, CancellationToken cancellationToken)
    {
        var generator = new TypeMatrixGenerator(sqlOptions);
        var (entries, serverVersion) = await generator.GenerateAsync(
            TypeMatrixGenerator.NumericFamily,
            TypeMatrixGenerator.DateTimeFamily,
            TypeMatrixGenerator.StringFamily,
            TypeMatrixGenerator.Collations,
            TypeMatrixGenerator.CrossFamilyOther,
            TypeMatrixGenerator.BinaryFamily,
            cancellationToken);

        var document = new
        {
            ServerVersion = serverVersion,
            ProbedAtUtc = DateTime.UtcNow.ToString("yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture),
            Notes = "Generated by SilentScan.Verify generate-type-matrix against the local Docker SQL Server, compat level 160, compile-only via SET SHOWPLAN_XML. "
                + "ColumnConverts=true means a CONVERT_IMPLICIT node targets the column (ConvertImplicitDetector). "
                + "DynamicRangeSeekAvailable=true means the plan contains an Intrinsic GetRangeThroughConvert node. "
                + "CompileFailed=true means SQL Server rejected the comparison outright (the pair is not implicitly comparable at all).",
            Entries = entries,
        };

        var json = JsonSerializer.Serialize(document, JsonOptions);
        await File.WriteAllTextAsync(outputPath, json + Environment.NewLine, cancellationToken);
        await stdout.WriteLineAsync($"Wrote {entries.Count} entries (server {serverVersion}) to {outputPath}");

        return 0;
    }
}
