using SilentScan.Core.Catalog;
using SilentScan.Core.Diagnostics;
using SilentScan.Core.Lineage;
using SilentScan.Core.Parsing;
using SilentScan.Core.Predicates;
using SilentScan.Core.Reporting;
using SilentScan.Core.Rules;
using SilentScan.Core.TypeInference;

namespace SilentScan.Tests.Support;

public static class TestScanReports
{
    public static ScanReport Build(
        ParseHealthReport? ParseHealth = null,
        IReadOnlyList<SargabilityFinding>? Tier1Findings = null,
        IReadOnlyList<TypedPredicateFinding>? TypedFindings = null,
        IReadOnlyList<DynamicSqlFinding>? DynamicSqlFindings = null,
        IReadOnlyList<ExpressionDerivedFinding>? ExpressionDerivedFindings = null,
        IReadOnlyList<CollationConflictFinding>? CollationConflictFindings = null,
        IReadOnlyList<WriteLossFinding>? WriteLossFindings = null,
        IReadOnlyList<TvfFenceFinding>? TvfFenceFindings = null,
        IReadOnlyList<ScalarUdfFinding>? ScalarUdfFindings = null,
        IReadOnlyList<ColumnCollationDriftFinding>? ColumnCollationDriftFindings = null,
        IReadOnlyList<CrossTableTypeDriftFinding>? CrossTableTypeDriftFindings = null,
        IReadOnlyList<ProcCallArgumentMismatchFinding>? ProcCallArgumentMismatchFindings = null,
        IReadOnlyList<TemporalBoundaryPrecisionFinding>? TemporalBoundaryFindings = null,
        IReadOnlyList<MaxTypedColumnFinding>? MaxTypedColumnFindings = null,
        IReadOnlyList<OversizedParameterFinding>? OversizedParameterFindings = null,
        IReadOnlyList<UnderLengthParameterFinding>? UnderLengthParameterFindings = null,
        IReadOnlyList<AnsiPaddingMismatchFinding>? AnsiPaddingMismatchFindings = null,
        IReadOnlyList<PartialCompositeForeignKeyJoinFinding>? PartialCompositeForeignKeyJoinFindings = null,
        IReadOnlyList<SetOptionFinding>? SetOptionFindings = null,
        IReadOnlyList<CatchAllPredicateFinding>? CatchAllPredicateFindings = null,
        IReadOnlyList<LocalVariablePredicateFinding>? LocalVariablePredicateFindings = null,
        IReadOnlyList<FilteredIndexParameterMismatchFinding>? FilteredIndexParameterMismatchFindings = null,
        IReadOnlyList<NotInNullableSubqueryFinding>? NotInNullableSubqueryFindings = null,
        IReadOnlyList<NonUniqueUpdateSourceFinding>? NonUniqueUpdateSourceFindings = null,
        IReadOnlyList<ForcedSerialFinding>? ForcedSerialFindings = null,
        IReadOnlyList<UntrustedConstraintFinding>? UntrustedConstraintFindings = null,
        IReadOnlyList<CascadingForeignKeyFinding>? CascadingForeignKeyFindings = null,
        IReadOnlyList<MultiReferencedCteFinding>? MultiReferencedCteFindings = null,
        IReadOnlyList<NestedViewDepthFinding>? NestedViewDepthFindings = null,
        IReadOnlyList<PostExpansionJoinWidthFinding>? PostExpansionJoinWidthFindings = null,
        IReadOnlyList<SelectStarViewFinding>? SelectStarViewFindings = null,
        IReadOnlyList<UnparameterizedDynamicSqlFinding>? UnparameterizedDynamicSqlFindings = null,
        IReadOnlyList<NonPersistedComputedColumnFinding>? NonPersistedComputedColumnFindings = null,
        IReadOnlyList<TempTableExecShapeFinding>? TempTableExecShapeFindings = null,
        IReadOnlyList<SelfReferencingDmlFinding>? SelfReferencingDmlFindings = null,
        IReadOnlyList<TemporalTableHistoryIndexGapFinding>? TemporalTableHistoryIndexGapFindings = null,
        IReadOnlyList<ModuleCompileFlagFinding>? ModuleCompileFlagFindings = null,
        IReadOnlyList<WindowFrameFinding>? WindowFrameFindings = null,
        IReadOnlyList<WaitForFinding>? WaitForFindings = null,
        IReadOnlyList<ViewOrderingFinding>? ViewOrderingFindings = null,
        IReadOnlyList<TransactionHygieneFinding>? TransactionHygieneFindings = null,
        IReadOnlyList<CompositeIndexLeadingColumnFinding>? CompositeIndexLeadingColumnFindings = null,
        IReadOnlyList<IndexHintFinding>? IndexHintFindings = null,
        IReadOnlyList<SessionDateSettingFinding>? SessionDateSettingFindings = null,
        IReadOnlyList<CartesianJoinFinding>? CartesianJoinFindings = null,
        IReadOnlyList<UndersizedDeclarationFinding>? UndersizedDeclarationFindings = null,
        IReadOnlyList<TruncateSwallowedFinding>? TruncateSwallowedFindings = null,
        IReadOnlyList<UnindexedTempTableUsageFinding>? UnindexedTempTableUsageFindings = null,
        IReadOnlyList<OutputParameterFinding>? OutputParameterFindings = null,
        IReadOnlyList<DatabaseConfigurationFinding>? DatabaseConfigurationFindings = null,
        IReadOnlyList<ParameterReassignmentPredicateFinding>? ParameterReassignmentPredicateFindings = null,
        IReadOnlyList<CodeMetricFinding>? CodeMetricFindings = null,
        IReadOnlyList<FormattingFinding>? FormattingFindings = null,
        IReadOnlyList<NamingFinding>? NamingFindings = null,
        IReadOnlyList<DeadCodeFinding>? DeadCodeFindings = null,
        IReadOnlyList<DuplicationFinding>? DuplicationFindings = null,
        IReadOnlyList<DeprecatedSyntaxFinding>? DeprecatedSyntaxFindings = null,
        IReadOnlyList<StatementShapeFinding>? StatementShapeFindings = null,
        IReadOnlyList<ControlFlowRiskFinding>? ControlFlowRiskFindings = null,
        IReadOnlyList<SecurityFinding>? SecurityFindings = null,
        IReadOnlyList<IndexDesignFinding>? IndexDesignFindings = null,
        IReadOnlyList<IdentityRangeFinding>? IdentityRangeFindings = null,
        IReadOnlyList<FloatEqualityFinding>? FloatEqualityFindings = null,
        IReadOnlyList<QueryAntiPatternFinding>? QueryAntiPatternFindings = null,
        IReadOnlyList<IndexCoverageFinding>? IndexCoverageFindings = null,
        IReadOnlyList<TriggerCorrectnessFinding>? TriggerCorrectnessFindings = null,
        IReadOnlyList<CrossModuleLockOrderFinding>? CrossModuleLockOrderFindings = null,
        IReadOnlyList<TriggerRecursionCycleFinding>? TriggerRecursionCycleFindings = null,
        IReadOnlyList<CheckConstraintFinding>? CheckConstraintFindings = null,
        IReadOnlyList<DefaultNullableConstraintFinding>? DefaultNullableConstraintFindings = null,
        IReadOnlyList<TryCastComputedColumnPredicateFinding>? TryCastComputedColumnPredicateFindings = null,
        IReadOnlyList<StaleSelectStarViewFinding>? StaleSelectStarViewFindings = null,
        IReadOnlyList<BareTopNoOrderByFinding>? BareTopNoOrderByFindings = null,
        IReadOnlyList<StringConcatNullFinding>? StringConcatNullFindings = null,
        IReadOnlyList<AggregateDivisionColumnstoreFinding>? AggregateDivisionColumnstoreFindings = null,
        IReadOnlyList<SecurityPredicateIndexFinding>? SecurityPredicateIndexFindings = null,
        IReadOnlyList<DanglingObjectReferenceFinding>? DanglingObjectReferenceFindings = null,
        IReadOnlyList<ForcedParameterizationFinding>? ForcedParameterizationFindings = null,
        IReadOnlyList<ColumnstoreUnsupportedColumnTypeFinding>? ColumnstoreUnsupportedColumnTypeFindings = null,
        IReadOnlyList<AlwaysEncryptedOrderByFinding>? AlwaysEncryptedOrderByFindings = null,
        IReadOnlyList<TriggerOrderFinding>? TriggerOrderFindings = null,
        IReadOnlyList<MissingStatisticsFinding>? MissingStatisticsFindings = null,
        IReadOnlyList<OperandComparabilityFinding>? OperandComparabilityFindings = null,
        IReadOnlyList<MemoryOptimizedUnsupportedColumnTypeFinding>? MemoryOptimizedUnsupportedColumnTypeFindings = null,
        IReadOnlyList<MemoryOptimizedUnsupportedIndexOptionFinding>? MemoryOptimizedUnsupportedIndexOptionFindings = null,
        IReadOnlyList<MemoryOptimizedForeignKeyFinding>? MemoryOptimizedForeignKeyFindings = null,
        IReadOnlyList<WindowFunctionArgumentFinding>? WindowFunctionArgumentFindings = null,
        IReadOnlyList<SelectiveXmlIndexValueColumnFinding>? SelectiveXmlIndexValueColumnFindings = null,
        IReadOnlyList<FloatOrderDependentAggregateFinding>? FloatOrderDependentAggregateFindings = null,
        IReadOnlyList<SkippedConstruct>? SkippedConstructs = null,
        SkippedConstructSummary? SkippedConstructSummary = null,
        TypedPredicateSummary? TypedPredicateSummary = null,
        DynamicSqlSummary? DynamicSqlSummary = null,
        int SchemaVersion = ScanReport.CurrentSchemaVersion)
    {
        return new ScanReport(
            ParseHealth ?? new ParseHealthReport([]),
            Tier1Findings ?? [],
            TypedFindings ?? [],
            DynamicSqlFindings ?? [],
            ExpressionDerivedFindings ?? [],
            CollationConflictFindings ?? [],
            WriteLossFindings ?? [],
            TvfFenceFindings ?? [],
            ScalarUdfFindings ?? [],
            ColumnCollationDriftFindings ?? [],
            CrossTableTypeDriftFindings ?? [],
            ProcCallArgumentMismatchFindings ?? [],
            TemporalBoundaryFindings ?? [],
            MaxTypedColumnFindings ?? [],
            OversizedParameterFindings ?? [],
            UnderLengthParameterFindings ?? [],
            AnsiPaddingMismatchFindings ?? [],
            PartialCompositeForeignKeyJoinFindings ?? [],
            SetOptionFindings ?? [],
            CatchAllPredicateFindings ?? [],
            LocalVariablePredicateFindings ?? [],
            FilteredIndexParameterMismatchFindings ?? [],
            NotInNullableSubqueryFindings ?? [],
            NonUniqueUpdateSourceFindings ?? [],
            ForcedSerialFindings ?? [],
            UntrustedConstraintFindings ?? [],
            CascadingForeignKeyFindings ?? [],
            MultiReferencedCteFindings ?? [],
            NestedViewDepthFindings ?? [],
            PostExpansionJoinWidthFindings ?? [],
            SelectStarViewFindings ?? [],
            UnparameterizedDynamicSqlFindings ?? [],
            NonPersistedComputedColumnFindings ?? [],
            TempTableExecShapeFindings ?? [],
            SelfReferencingDmlFindings ?? [],
            TemporalTableHistoryIndexGapFindings ?? [],
            ModuleCompileFlagFindings ?? [],
            WindowFrameFindings ?? [],
            WaitForFindings ?? [],
            ViewOrderingFindings ?? [],
            TransactionHygieneFindings ?? [],
            CompositeIndexLeadingColumnFindings ?? [],
            IndexHintFindings ?? [],
            SessionDateSettingFindings ?? [],
            CartesianJoinFindings ?? [],
            UndersizedDeclarationFindings ?? [],
            TruncateSwallowedFindings ?? [],
            UnindexedTempTableUsageFindings ?? [],
            OutputParameterFindings ?? [],
            DatabaseConfigurationFindings ?? [],
            ParameterReassignmentPredicateFindings ?? [],
            CodeMetricFindings ?? [],
            FormattingFindings ?? [],
            NamingFindings ?? [],
            DeadCodeFindings ?? [],
            DuplicationFindings ?? [],
            DeprecatedSyntaxFindings ?? [],
            StatementShapeFindings ?? [],
            ControlFlowRiskFindings ?? [],
            SecurityFindings ?? [],
            IndexDesignFindings ?? [],
            IdentityRangeFindings ?? [],
            FloatEqualityFindings ?? [],
            QueryAntiPatternFindings ?? [],
            IndexCoverageFindings ?? [],
            TriggerCorrectnessFindings ?? [],
            CrossModuleLockOrderFindings ?? [],
            TriggerRecursionCycleFindings ?? [],
            CheckConstraintFindings ?? [],
            DefaultNullableConstraintFindings ?? [],
            TryCastComputedColumnPredicateFindings ?? [],
            StaleSelectStarViewFindings ?? [],
            BareTopNoOrderByFindings ?? [],
            StringConcatNullFindings ?? [],
            AggregateDivisionColumnstoreFindings ?? [],
            SecurityPredicateIndexFindings ?? [],
            DanglingObjectReferenceFindings ?? [],
            ForcedParameterizationFindings ?? [],
            ColumnstoreUnsupportedColumnTypeFindings ?? [],
            AlwaysEncryptedOrderByFindings ?? [],
            TriggerOrderFindings ?? [],
            MissingStatisticsFindings ?? [],
            OperandComparabilityFindings ?? [],
            MemoryOptimizedUnsupportedColumnTypeFindings ?? [],
            MemoryOptimizedUnsupportedIndexOptionFindings ?? [],
            MemoryOptimizedForeignKeyFindings ?? [],
            WindowFunctionArgumentFindings ?? [],
            SelectiveXmlIndexValueColumnFindings ?? [],
            FloatOrderDependentAggregateFindings ?? [],
            SkippedConstructs ?? [],
            SkippedConstructSummary ?? SkippedConstructSummary.From([]),
            TypedPredicateSummary ?? TypedPredicateSummary.From([]),
            DynamicSqlSummary ?? DynamicSqlSummary.From([]),
            SchemaVersion);
    }
}
