namespace SilentScan.Core.Reporting.RuleDocs;

public static class RuleDocCatalog
{
    public static IReadOnlyDictionary<string, RuleDocContent> ByRuleId { get; } = new Dictionary<string, RuleDocContent>(StringComparer.Ordinal)
    {

        [Tier1.FunctionWrappedColumn.RuleId] = Tier1.FunctionWrappedColumn.Content,
        [Tier1.CastOrConvertOnColumn.RuleId] = Tier1.CastOrConvertOnColumn.Content,
        [Tier1.ColumnArithmetic.RuleId] = Tier1.ColumnArithmetic.Content,
        [Tier1.LeadingWildcardLike.RuleId] = Tier1.LeadingWildcardLike.Content,
        [Tier1.LikePatternNotLiteral.RuleId] = Tier1.LikePatternNotLiteral.Content,
        [Tier1.CaseFoldOnColumn.RuleId] = Tier1.CaseFoldOnColumn.Content,
        [Tier1.DateFunctionOnColumn.RuleId] = Tier1.DateFunctionOnColumn.Content,
        [Tier1.CharindexOrLeftOnColumn.RuleId] = Tier1.CharindexOrLeftOnColumn.Content,

        [Verdict.ScanForced.RuleId] = Verdict.ScanForced.Content,
        [Verdict.RangeSeek.RuleId] = Verdict.RangeSeek.Content,

        [WriteLoss.UnicodeReplacement.RuleId] = WriteLoss.UnicodeReplacement.Content,
        [WriteLoss.ApproximateTruncation.RuleId] = WriteLoss.ApproximateTruncation.Content,
        [WriteLoss.NumericScaleNarrowing.RuleId] = WriteLoss.NumericScaleNarrowing.Content,
        [WriteLoss.TemporalPrecisionLoss.RuleId] = WriteLoss.TemporalPrecisionLoss.Content,
        [WriteLoss.LengthTruncation.RuleId] = WriteLoss.LengthTruncation.Content,
        [WriteLoss.TemporalScaleNarrowing.RuleId] = WriteLoss.TemporalScaleNarrowing.Content,
        [WriteLoss.TemporalOffsetDropped.RuleId] = WriteLoss.TemporalOffsetDropped.Content,

        [Correctness.NotInNullableSubquery.RuleId] = Correctness.NotInNullableSubquery.Content,
        [Correctness.NonUniqueUpdateSource.RuleId] = Correctness.NonUniqueUpdateSource.Content,
        [Correctness.TemporalBoundaryPrecision.RuleId] = Correctness.TemporalBoundaryPrecision.Content,
        [Join.PartialCompositeForeignKeyJoin.RuleId] = Join.PartialCompositeForeignKeyJoin.Content,
        [Join.CartesianCommaJoin.RuleId] = Join.CartesianCommaJoin.Content,
        [Join.CartesianCrossJoin.RuleId] = Join.CartesianCrossJoin.Content,
        [Dml.SelfReferencingDml.RuleId] = Dml.SelfReferencingDml.Content,
        [Index.KeyLookupProneIndex.RuleId] = Index.KeyLookupProneIndex.Content,
        [Predicate.StringConcatNull.RuleId] = Predicate.StringConcatNull.Content,

        [Naming.ReservedKeywordAsIdentifier.RuleId] = Naming.ReservedKeywordAsIdentifier.Content,
        [Naming.SpPrefixOnUserRoutine.RuleId] = Naming.SpPrefixOnUserRoutine.Content,
        [Naming.UnqualifiedCreate.RuleId] = Naming.UnqualifiedCreate.Content,
        [Naming.RedundantTypeQualifier.RuleId] = Naming.RedundantTypeQualifier.Content,

        [SessionDate.SetDateFormat.RuleId] = SessionDate.SetDateFormat.Content,
        [SessionDate.SetDateFirst.RuleId] = SessionDate.SetDateFirst.Content,

        [Hint.IndexDoesNotExist.RuleId] = Hint.IndexDoesNotExist.Content,
        [Hint.HintedIndexNotSeekable.RuleId] = Hint.HintedIndexNotSeekable.Content,

        [WindowFrame.ExplicitRangeFrame.RuleId] = WindowFrame.ExplicitRangeFrame.Content,
        [WindowFrame.ImplicitDefaultRangeFrame.RuleId] = WindowFrame.ImplicitDefaultRangeFrame.Content,
        [WindowFunctionArgument.LagLeadNegativeOffset.RuleId] = WindowFunctionArgument.LagLeadNegativeOffset.Content,
        [WindowFunctionArgument.PercentileOutOfRange.RuleId] = WindowFunctionArgument.PercentileOutOfRange.Content,
        [Query.BareTopNoOrderBy.RuleId] = Query.BareTopNoOrderBy.Content,

        [QueryAntiPattern.TableVariablePspSkip.RuleId] = QueryAntiPattern.TableVariablePspSkip.Content,
        [QueryAntiPattern.TableVariableLowCompatEstimate.RuleId] = QueryAntiPattern.TableVariableLowCompatEstimate.Content,
        [QueryAntiPattern.TableVariableStaleEstimateInLoop.RuleId] = QueryAntiPattern.TableVariableStaleEstimateInLoop.Content,
        [QueryAntiPattern.RbarSingleRowLoopDml.RuleId] = QueryAntiPattern.RbarSingleRowLoopDml.Content,
        [QueryAntiPattern.GlobalCursorDeclaration.RuleId] = QueryAntiPattern.GlobalCursorDeclaration.Content,
        [QueryAntiPattern.CountStarVariableExistenceCheck.RuleId] = QueryAntiPattern.CountStarVariableExistenceCheck.Content,
        [QueryAntiPattern.NonAggregateHavingPredicate.RuleId] = QueryAntiPattern.NonAggregateHavingPredicate.Content,
        [QueryAntiPattern.UnionOfProvablyDisjointBranches.RuleId] = QueryAntiPattern.UnionOfProvablyDisjointBranches.Content,
        [QueryAntiPattern.DistinctMaskingJoinFanout.RuleId] = QueryAntiPattern.DistinctMaskingJoinFanout.Content,
        [QueryAntiPattern.UnqualifiedTableReference.RuleId] = QueryAntiPattern.UnqualifiedTableReference.Content,
        [QueryAntiPattern.MergeMissingHoldlock.RuleId] = QueryAntiPattern.MergeMissingHoldlock.Content,
        [QueryAntiPattern.MergeNonUniqueUsingSource.RuleId] = QueryAntiPattern.MergeNonUniqueUsingSource.Content,
        [QueryAntiPattern.MergeUnconditionalDelete.RuleId] = QueryAntiPattern.MergeUnconditionalDelete.Content,
        [QueryAntiPattern.RecursiveCteMissingMaxRecursion.RuleId] = QueryAntiPattern.RecursiveCteMissingMaxRecursion.Content,
        [QueryAntiPattern.UnboundedTableWrite.RuleId] = QueryAntiPattern.UnboundedTableWrite.Content,
        [QueryAntiPattern.LinkedServerOrCrossDatabaseReference.RuleId] = QueryAntiPattern.LinkedServerOrCrossDatabaseReference.Content,
        [QueryAntiPattern.MultiRowInsertIgnoreDupKeyDrop.RuleId] = QueryAntiPattern.MultiRowInsertIgnoreDupKeyDrop.Content,
        [QueryAntiPattern.AlterTableSwitchColumnMismatch.RuleId] = QueryAntiPattern.AlterTableSwitchColumnMismatch.Content,
        [QueryAntiPattern.AlterTableSwitchIndexMismatch.RuleId] = QueryAntiPattern.AlterTableSwitchIndexMismatch.Content,
        [QueryAntiPattern.AlterTableSwitchConstraintMismatch.RuleId] = QueryAntiPattern.AlterTableSwitchConstraintMismatch.Content,
        [QueryAntiPattern.AlterTableSwitchTargetOnlyIndexRestriction.RuleId] = QueryAntiPattern.AlterTableSwitchTargetOnlyIndexRestriction.Content,
        [QueryAntiPattern.AlterTableSwitchFilegroupMismatch.RuleId] = QueryAntiPattern.AlterTableSwitchFilegroupMismatch.Content,
        [QueryAntiPattern.AlterTableSwitchTemporalMismatch.RuleId] = QueryAntiPattern.AlterTableSwitchTemporalMismatch.Content,
        [QueryAntiPattern.AlterTableSwitchRuleConstraint.RuleId] = QueryAntiPattern.AlterTableSwitchRuleConstraint.Content,
        [QueryAntiPattern.AlterTableSwitchCdcPartitionSwitch.RuleId] = QueryAntiPattern.AlterTableSwitchCdcPartitionSwitch.Content,
        [QueryAntiPattern.AlterTableSwitchPartitionFilegroupMismatch.RuleId] = QueryAntiPattern.AlterTableSwitchPartitionFilegroupMismatch.Content,
        [QueryAntiPattern.AlterTableSwitchFullTextIndexRestriction.RuleId] = QueryAntiPattern.AlterTableSwitchFullTextIndexRestriction.Content,
        [QueryAntiPattern.GroupingSetsCardinalityLimitExceeded.RuleId] = QueryAntiPattern.GroupingSetsCardinalityLimitExceeded.Content,

        [TriggerCorrectness.MultiRowUnsafeSingleRowAssignment.RuleId] = TriggerCorrectness.MultiRowUnsafeSingleRowAssignment.Content,
        [TriggerCorrectness.MultiRowUnsafeKeyedDml.RuleId] = TriggerCorrectness.MultiRowUnsafeKeyedDml.Content,
        [TriggerCorrectness.NoEarlyOutForEmptyInvocation.RuleId] = TriggerCorrectness.NoEarlyOutForEmptyInvocation.Content,
        [TriggerCorrectness.DirectRecursiveTrigger.RuleId] = TriggerCorrectness.DirectRecursiveTrigger.Content,
        [TriggerCorrectness.InsteadOfInsertFilteredNoRejectPath.RuleId] = TriggerCorrectness.InsteadOfInsertFilteredNoRejectPath.Content,
        [TriggerCorrectness.UpdateFunctionWithoutValueComparison.RuleId] = TriggerCorrectness.UpdateFunctionWithoutValueComparison.Content,
        [TriggerCorrectness.LogonTriggerHostNameGate.RuleId] = TriggerCorrectness.LogonTriggerHostNameGate.Content,
        [ForcedSerial.TableVariableModification.RuleId] = ForcedSerial.TableVariableModification.Content,
        [ForcedSerial.FastForwardCursor.RuleId] = ForcedSerial.FastForwardCursor.Content,
        [ForcedSerial.NonParallelizableIntrinsic.RuleId] = ForcedSerial.NonParallelizableIntrinsic.Content,
        [CrossModule.InconsistentLockOrder.RuleId] = CrossModule.InconsistentLockOrder.Content,
        [Trigger.MultiHopRecursionCycle.RuleId] = Trigger.MultiHopRecursionCycle.Content,

        [TvfFence.CorrelatedApply.RuleId] = TvfFence.CorrelatedApply.Content,
        [TvfFence.NestedUnderViewOrTvf.RuleId] = TvfFence.NestedUnderViewOrTvf.Content,
        [TvfFence.FromOrJoin.RuleId] = TvfFence.FromOrJoin.Content,
        [TvfFence.InsertExec.RuleId] = TvfFence.InsertExec.Content,
        [TvfFence.Standalone.RuleId] = TvfFence.Standalone.Content,
        [ScalarUdf.PredicateInvocation.RuleId] = ScalarUdf.PredicateInvocation.Content,
        [ScalarUdf.NestedUnderViewOrTvf.RuleId] = ScalarUdf.NestedUnderViewOrTvf.Content,
        [ScalarUdf.SchemaDependency.RuleId] = ScalarUdf.SchemaDependency.Content,
        [ScalarUdf.ProjectionInvocation.RuleId] = ScalarUdf.ProjectionInvocation.Content,
        [Catalog.ColumnCollationDrift.RuleId] = Catalog.ColumnCollationDrift.Content,
        [Catalog.CrossTableFkTypeDrift.RuleId] = Catalog.CrossTableFkTypeDrift.Content,
        [CallGraph.ArgumentTypeMismatch.RuleId] = CallGraph.ArgumentTypeMismatch.Content,
        [Catalog.MaxTypedColumn.RuleId] = Catalog.MaxTypedColumn.Content,
        [Catalog.SelectiveXmlIndexValueColumn.RuleId] = Catalog.SelectiveXmlIndexValueColumn.Content,
        [Catalog.ColumnstoreUnsupportedColumnType.RuleId] = Catalog.ColumnstoreUnsupportedColumnType.Content,
        [Catalog.RecompilesEveryCall.RuleId] = Catalog.RecompilesEveryCall.Content,
        [Catalog.TableValuedFunctionReturnUsesDatabaseCollation.RuleId] = Catalog.TableValuedFunctionReturnUsesDatabaseCollation.Content,
        [Catalog.DanglingObjectReference.RuleId] = Catalog.DanglingObjectReference.Content,
        [Predicates.FloatEquality.RuleId] = Predicates.FloatEquality.Content,
        [Predicates.FloatOrderDependentAggregate.RuleId] = Predicates.FloatOrderDependentAggregate.Content,
        [Predicates.AlwaysEncryptedOrderBy.RuleId] = Predicates.AlwaysEncryptedOrderBy.Content,
        [Predicates.AlwaysEncryptedKeyColumn.RuleId] = Predicates.AlwaysEncryptedKeyColumn.Content,
        [Predicates.AlterColumnPrecisionScaleNarrowing.RuleId] = Predicates.AlterColumnPrecisionScaleNarrowing.Content,
        [Predicates.AlterColumnIncompatibleFamilyConversion.RuleId] = Predicates.AlterColumnIncompatibleFamilyConversion.Content,
        [Predicates.XmlOperandNotComparable.RuleId] = Predicates.XmlOperandNotComparable.Content,
        [Predicates.LegacyLobOperandNotComparable.RuleId] = Predicates.LegacyLobOperandNotComparable.Content,

        [Catalog.UntrustedForeignKey.RuleId] = Catalog.UntrustedForeignKey.Content,
        [Catalog.UntrustedCheckConstraint.RuleId] = Catalog.UntrustedCheckConstraint.Content,
        [Catalog.CheckConstraintNullNotHandled.RuleId] = Catalog.CheckConstraintNullNotHandled.Content,
        [Catalog.CheckConstraintOnIdentityColumn.RuleId] = Catalog.CheckConstraintOnIdentityColumn.Content,
        [Catalog.DefaultConstraintOnNullableColumn.RuleId] = Catalog.DefaultConstraintOnNullableColumn.Content,
        [Predicates.CatchAllParameter.RuleId] = Predicates.CatchAllParameter.Content,
        [Predicates.LocalVariablePredicate.RuleId] = Predicates.LocalVariablePredicate.Content,
        [Predicates.FilteredIndexParameterMismatch.RuleId] = Predicates.FilteredIndexParameterMismatch.Content,
        [Predicates.ReassignedParameter.RuleId] = Predicates.ReassignedParameter.Content,
        [Predicates.OversizedParameter.RuleId] = Predicates.OversizedParameter.Content,
        [Predicates.UnderLengthParameter.RuleId] = Predicates.UnderLengthParameter.Content,
        [Predicates.AnsiPaddingMismatch.RuleId] = Predicates.AnsiPaddingMismatch.Content,

        [View.TopPercentOrderByNeverLimits.RuleId] = View.TopPercentOrderByNeverLimits.Content,
        [View.OrderByNotGuaranteedToConsumer.RuleId] = View.OrderByNotGuaranteedToConsumer.Content,

        [TempTable.UnindexedJoinOperand.RuleId] = TempTable.UnindexedJoinOperand.Content,
        [TempTable.UnindexedWhereFilter.RuleId] = TempTable.UnindexedWhereFilter.Content,

        [Identity.RangeNearExhaustion.RuleId] = Identity.RangeNearExhaustion.Content,

        [Security.HardCodedCredential.RuleId] = Security.HardCodedCredential.Content,
        [Security.HardCodedIpAddress.RuleId] = Security.HardCodedIpAddress.Content,
        [Security.WeakHashAlgorithm.RuleId] = Security.WeakHashAlgorithm.Content,
        [Security.WeakHashAlgorithmInSensitiveContext.RuleId] = Security.WeakHashAlgorithmInSensitiveContext.Content,
        [Security.UnprovableDynamicSqlText.RuleId] = Security.UnprovableDynamicSqlText.Content,

        [ControlFlow.CursorFetchColumnCountMismatch.RuleId] = ControlFlow.CursorFetchColumnCountMismatch.Content,
        [ControlFlow.EmptyCatchBlock.RuleId] = ControlFlow.EmptyCatchBlock.Content,
        [ControlFlow.TriggerEmitsOutput.RuleId] = ControlFlow.TriggerEmitsOutput.Content,
        [ControlFlow.DirtyReadIsolationHint.RuleId] = ControlFlow.DirtyReadIsolationHint.Content,
        [ControlFlow.DuplicatedCallArgument.RuleId] = ControlFlow.DuplicatedCallArgument.Content,
        [ControlFlow.LegacyIdentityIntrinsic.RuleId] = ControlFlow.LegacyIdentityIntrinsic.Content,
        [ControlFlow.GotoUsage.RuleId] = ControlFlow.GotoUsage.Content,
        [ControlFlow.CaseExpressionMissingElse.RuleId] = ControlFlow.CaseExpressionMissingElse.Content,
        [ControlFlow.NonDeterministicCaseInput.RuleId] = ControlFlow.NonDeterministicCaseInput.Content,
        [ControlFlow.WaitFor.RuleId] = ControlFlow.WaitFor.Content,
        [ControlFlow.TransactionHygiene.RuleId] = ControlFlow.TransactionHygiene.Content,
        [ControlFlow.TruncateSwallowed.RuleId] = ControlFlow.TruncateSwallowed.Content,
        [ControlFlow.OutputParameter.RuleId] = ControlFlow.OutputParameter.Content,

        [StatementShape.InsertWithoutColumnList.RuleId] = StatementShape.InsertWithoutColumnList.Content,
        [StatementShape.OrdinalOrderBy.RuleId] = StatementShape.OrdinalOrderBy.Content,
        [StatementShape.TableWithNoPrimaryKey.RuleId] = StatementShape.TableWithNoPrimaryKey.Content,
        [StatementShape.MissingSetNocountOn.RuleId] = StatementShape.MissingSetNocountOn.Content,
        [StatementShape.BareSelectStar.RuleId] = StatementShape.BareSelectStar.Content,

        [Database.PageVerifyNotChecksum.RuleId] = Database.PageVerifyNotChecksum.Content,
        [Database.AutoShrinkOn.RuleId] = Database.AutoShrinkOn.Content,
        [Database.AutoCloseOn.RuleId] = Database.AutoCloseOn.Content,
        [Database.TargetRecoveryTimeUnset.RuleId] = Database.TargetRecoveryTimeUnset.Content,
        [Database.QueryStoreNotReadWrite.RuleId] = Database.QueryStoreNotReadWrite.Content,
        [Database.QueryStoreCaptureModeNotAuto.RuleId] = Database.QueryStoreCaptureModeNotAuto.Content,
        [Database.AutoCreateStatisticsOff.RuleId] = Database.AutoCreateStatisticsOff.Content,
        [Database.AutoUpdateStatisticsOff.RuleId] = Database.AutoUpdateStatisticsOff.Content,
        [Database.CompatibilityLevelBehindEngineDefault.RuleId] = Database.CompatibilityLevelBehindEngineDefault.Content,
        [Database.SpatialPersistedComputedColumnCompatibilityChange.RuleId] = Database.SpatialPersistedComputedColumnCompatibilityChange.Content,

        [Lineage.ExpressionDerivedColumn.RuleId] = Lineage.ExpressionDerivedColumn.Content,
        [Lineage.MultiReferencedCte.RuleId] = Lineage.MultiReferencedCte.Content,
        [Lineage.NestedViewDepth.RuleId] = Lineage.NestedViewDepth.Content,
        [Lineage.PostExpansionJoinWidth.RuleId] = Lineage.PostExpansionJoinWidth.Content,
        [Lineage.SelectStarView.RuleId] = Lineage.SelectStarView.Content,

        [DynamicSql.Analyzed.RuleId] = DynamicSql.Analyzed.Content,
        [DynamicSql.Unanalyzable.RuleId] = DynamicSql.Unanalyzable.Content,
        [DynamicSql.InnerParseFailed.RuleId] = DynamicSql.InnerParseFailed.Content,
        [DynamicSql.PartiallyAnalyzed.RuleId] = DynamicSql.PartiallyAnalyzed.Content,
        [DynamicSql.ConcatenatedValueInConstantSql.RuleId] = DynamicSql.ConcatenatedValueInConstantSql.Content,
        [DynamicSql.ExecStringConcatenatesParameterizableValue.RuleId] = DynamicSql.ExecStringConcatenatesParameterizableValue.Content,
        [DynamicSql.TempTableExecShapeColumnCountMismatch.RuleId] = DynamicSql.TempTableExecShapeColumnCountMismatch.Content,
        [DynamicSql.TempTableExecShapeColumnTypeMismatch.RuleId] = DynamicSql.TempTableExecShapeColumnTypeMismatch.Content,

        [Catalog.CascadingForeignKey.RuleId] = Catalog.CascadingForeignKey.Content,
        [Catalog.NonPersistedComputedColumn.RuleId] = Catalog.NonPersistedComputedColumn.Content,
        [Catalog.TemporalTableHistoryIndexGap.RuleId] = Catalog.TemporalTableHistoryIndexGap.Content,
        [Catalog.StaleSelectStarView.RuleId] = Catalog.StaleSelectStarView.Content,
        [Catalog.SecurityPredicateIndex.RuleId] = Catalog.SecurityPredicateIndex.Content,
        [Predicate.TryCastComputedColumn.RuleId] = Predicate.TryCastComputedColumn.Content,
        [Predicate.AggregateDivisionColumnstore.RuleId] = Predicate.AggregateDivisionColumnstore.Content,

        [IndexDesign.HeapWithNonclusteredIndexes.RuleId] = IndexDesign.HeapWithNonclusteredIndexes.Content,
        [IndexDesign.HeapWithNonclusteredPrimaryKey.RuleId] = IndexDesign.HeapWithNonclusteredPrimaryKey.Content,
        [IndexDesign.NonUniqueClusteredIndex.RuleId] = IndexDesign.NonUniqueClusteredIndex.Content,
        [IndexDesign.RandomClusteredKeyGuidDefault.RuleId] = IndexDesign.RandomClusteredKeyGuidDefault.Content,
        [IndexDesign.DuplicateIndex.RuleId] = IndexDesign.DuplicateIndex.Content,
        [IndexDesign.SubsumedIndex.RuleId] = IndexDesign.SubsumedIndex.Content,
        [IndexDesign.UnindexedForeignKey.RuleId] = IndexDesign.UnindexedForeignKey.Content,
        [IndexDesign.DisabledIndex.RuleId] = IndexDesign.DisabledIndex.Content,
        [IndexDesign.HypotheticalIndex.RuleId] = IndexDesign.HypotheticalIndex.Content,
        [IndexDesign.FilterColumnNotInIndex.RuleId] = IndexDesign.FilterColumnNotInIndex.Content,
        [IndexDesign.DeprecatedLobColumnType.RuleId] = IndexDesign.DeprecatedLobColumnType.Content,
        [IndexDesign.TimestampColumnNaming.RuleId] = IndexDesign.TimestampColumnNaming.Content,
        [IndexDesign.FloatOrRealIndexKeyColumn.RuleId] = IndexDesign.FloatOrRealIndexKeyColumn.Content,
        [IndexDesign.NoRecomputeStatistics.RuleId] = IndexDesign.NoRecomputeStatistics.Content,
        [IndexDesign.VariableLengthKeyColumnExceedsKeyLimit.RuleId] = IndexDesign.VariableLengthKeyColumnExceedsKeyLimit.Content,
        [IndexDesign.MergeableIndexesDifferingIncludeOnly.RuleId] = IndexDesign.MergeableIndexesDifferingIncludeOnly.Content,
        [IndexDesign.ColumnstoreIndexOnDmlTargetTable.RuleId] = IndexDesign.ColumnstoreIndexOnDmlTargetTable.Content,
        [IndexDesign.MonotonicClusteredKeyMissingSequentialOptimization.RuleId] = IndexDesign.MonotonicClusteredKeyMissingSequentialOptimization.Content,
        [IndexDesign.NonAlignedPartitionedIndex.RuleId] = IndexDesign.NonAlignedPartitionedIndex.Content,
        [ForcedParameterization.LikePatternLiteral.RuleId] = ForcedParameterization.LikePatternLiteral.Content,
        [ForcedParameterization.TopOrPagingLiteral.RuleId] = ForcedParameterization.TopOrPagingLiteral.Content,
        [ForcedParameterization.SelectListLiteral.RuleId] = ForcedParameterization.SelectListLiteral.Content,
        [ForcedParameterization.HavingLiteral.RuleId] = ForcedParameterization.HavingLiteral.Content,
        [ForcedParameterization.OrderByExpressionLiteral.RuleId] = ForcedParameterization.OrderByExpressionLiteral.Content,
        [ForcedParameterization.DoubleColonCallArgumentLiteral.RuleId] = ForcedParameterization.DoubleColonCallArgumentLiteral.Content,
        [ForcedParameterization.TableSampleSizeLiteral.RuleId] = ForcedParameterization.TableSampleSizeLiteral.Content,
        [ForcedParameterization.DmlOutputListLiteral.RuleId] = ForcedParameterization.DmlOutputListLiteral.Content,
        [ForcedParameterization.ConvertStyleCodeLiteral.RuleId] = ForcedParameterization.ConvertStyleCodeLiteral.Content,
        [ForcedParameterization.CheckSumArgumentLiteral.RuleId] = ForcedParameterization.CheckSumArgumentLiteral.Content,
        [ForcedParameterization.ConstantFoldableExpressionLiteral.RuleId] = ForcedParameterization.ConstantFoldableExpressionLiteral.Content,
        [ForcedParameterization.GroupByExpressionLiteral.RuleId] = ForcedParameterization.GroupByExpressionLiteral.Content,

        [DeadCode.UnreachableCode.RuleId] = DeadCode.UnreachableCode.Content,
        [DeadCode.UnusedLabel.RuleId] = DeadCode.UnusedLabel.Content,
        [DeadCode.UnusedLocalVariable.RuleId] = DeadCode.UnusedLocalVariable.Content,
        [DeadCode.UnusedParameter.RuleId] = DeadCode.UnusedParameter.Content,
        [DeadCode.RedundantJump.RuleId] = DeadCode.RedundantJump.Content,

        [Verdict.CollationConflict.RuleId] = Verdict.CollationConflict.Content,
        [Catalog.TriggerOrder.RuleId] = Catalog.TriggerOrder.Content,
        [Catalog.MemoryOptimizedUnsupportedColumnType.RuleId] = Catalog.MemoryOptimizedUnsupportedColumnType.Content,
        [IndexShape.CompositeIndexLeadingColumn.RuleId] = IndexShape.CompositeIndexLeadingColumn.Content,
        [Statistics.MissingStatistics.RuleId] = Statistics.MissingStatistics.Content,

        [CodeMetric.LineTooLong.RuleId] = CodeMetric.LineTooLong.Content,
        [CodeMetric.ModuleTooLong.RuleId] = CodeMetric.ModuleTooLong.Content,
        [CodeMetric.RoutineTooLong.RuleId] = CodeMetric.RoutineTooLong.Content,
        [CodeMetric.TooManyParameters.RuleId] = CodeMetric.TooManyParameters.Content,
        [CodeMetric.NestingTooDeep.RuleId] = CodeMetric.NestingTooDeep.Content,
        [CodeMetric.TooManyConditionalOperators.RuleId] = CodeMetric.TooManyConditionalOperators.Content,
        [CodeMetric.TooManyCaseBranches.RuleId] = CodeMetric.TooManyCaseBranches.Content,
        [CodeMetric.CaseBranchTooLong.RuleId] = CodeMetric.CaseBranchTooLong.Content,

        [Formatting.TabCharacterUsed.RuleId] = Formatting.TabCharacterUsed.Content,
        [Formatting.MultipleStatementsOnSameLine.RuleId] = Formatting.MultipleStatementsOnSameLine.Content,
        [Formatting.MultipleDeclarationsOnSameLine.RuleId] = Formatting.MultipleDeclarationsOnSameLine.Content,
        [Formatting.MissingBeginEndBlock.RuleId] = Formatting.MissingBeginEndBlock.Content,
        [Formatting.SingleLineConditionalBody.RuleId] = Formatting.SingleLineConditionalBody.Content,
        [Formatting.DanglingStatementAfterUnbracedBody.RuleId] = Formatting.DanglingStatementAfterUnbracedBody.Content,
        [Formatting.IfImmediatelyFollowingPriorBlockEnd.RuleId] = Formatting.IfImmediatelyFollowingPriorBlockEnd.Content,
        [Formatting.RedundantParentheses.RuleId] = Formatting.RedundantParentheses.Content,
        [Formatting.MissingFileHeaderComment.RuleId] = Formatting.MissingFileHeaderComment.Content,

        [DeprecatedSyntax.TaskCommentTodo.RuleId] = DeprecatedSyntax.TaskCommentTodo.Content,
        [DeprecatedSyntax.TaskCommentFixme.RuleId] = DeprecatedSyntax.TaskCommentFixme.Content,
        [DeprecatedSyntax.NonAnsiComparisonOperator.RuleId] = DeprecatedSyntax.NonAnsiComparisonOperator.Content,
        [DeprecatedSyntax.EqualsNullComparison.RuleId] = DeprecatedSyntax.EqualsNullComparison.Content,
        [DeprecatedSyntax.NotEqualsNullComparison.RuleId] = DeprecatedSyntax.NotEqualsNullComparison.Content,
        [DeprecatedSyntax.LikeWithNoWildcard.RuleId] = DeprecatedSyntax.LikeWithNoWildcard.Content,
        [DeprecatedSyntax.LegacySystemCompatibilityView.RuleId] = DeprecatedSyntax.LegacySystemCompatibilityView.Content,
        [DeprecatedSyntax.TableHintWithoutWith.RuleId] = DeprecatedSyntax.TableHintWithoutWith.Content,
        [DeprecatedSyntax.NumberedProcedureDefinition.RuleId] = DeprecatedSyntax.NumberedProcedureDefinition.Content,
        [DeprecatedSyntax.NumberedProcedureExecution.RuleId] = DeprecatedSyntax.NumberedProcedureExecution.Content,
        [DeprecatedSyntax.StringLiteralColumnAlias.RuleId] = DeprecatedSyntax.StringLiteralColumnAlias.Content,
        [DeprecatedSyntax.RemovedSecurityStoredProcedure.RuleId] = DeprecatedSyntax.RemovedSecurityStoredProcedure.Content,
        [DeprecatedSyntax.DeprecatedSetRowcount.RuleId] = DeprecatedSyntax.DeprecatedSetRowcount.Content,

        [Duplication.CommentedOutCode.RuleId] = Duplication.CommentedOutCode.Content,
        [Duplication.DuplicatedStringLiteral.RuleId] = Duplication.DuplicatedStringLiteral.Content,
        [Duplication.SingleIterationLoop.RuleId] = Duplication.SingleIterationLoop.Content,
        [Duplication.SelfAssignment.RuleId] = Duplication.SelfAssignment.Content,
        [Duplication.IdenticalBinaryOperands.RuleId] = Duplication.IdenticalBinaryOperands.Content,
        [Duplication.RepeatedUnaryOperator.RuleId] = Duplication.RepeatedUnaryOperator.Content,
        [Duplication.NegatedComparisonAsOpposite.RuleId] = Duplication.NegatedComparisonAsOpposite.Content,
        [Duplication.DuplicateSiblingCondition.RuleId] = Duplication.DuplicateSiblingCondition.Content,
        [Duplication.IdenticalBranchBodies.RuleId] = Duplication.IdenticalBranchBodies.Content,
        [Duplication.AllBranchesIdentical.RuleId] = Duplication.AllBranchesIdentical.Content,
        [Duplication.RedundantAndCondition.RuleId] = Duplication.RedundantAndCondition.Content,
        [Duplication.MutuallyExclusiveAndCondition.RuleId] = Duplication.MutuallyExclusiveAndCondition.Content,
        [Duplication.CollapsibleNestedIf.RuleId] = Duplication.CollapsibleNestedIf.Content,
        [Duplication.NestedConditionalExpression.RuleId] = Duplication.NestedConditionalExpression.Content,
        [Duplication.AlwaysTrueOrFalseLiteralComparison.RuleId] = Duplication.AlwaysTrueOrFalseLiteralComparison.Content,
    };
}
