using SilentScan.Core.Predicates;
using SilentScan.Core.Rules;

namespace SilentScan.Core.Reporting.Sarif;

public static class SarifRuleCatalog
{
    public const string DynamicSqlAnalyzedRuleId = FindingRuleIds.DynamicSqlAnalyzedRuleId;
    public const string DynamicSqlUnanalyzableRuleId = FindingRuleIds.DynamicSqlUnanalyzableRuleId;
    public const string DynamicSqlInnerParseFailedRuleId = FindingRuleIds.DynamicSqlInnerParseFailedRuleId;
    public const string DynamicSqlPartiallyAnalyzedRuleId = FindingRuleIds.DynamicSqlPartiallyAnalyzedRuleId;
    public const string ExpressionDerivedRuleId = FindingRuleIds.ExpressionDerivedRuleId;
    public const string CollationConflictRuleId = FindingRuleIds.CollationConflictRuleId;
    public const string WriteLossUnicodeReplacementRuleId = FindingRuleIds.WriteLossUnicodeReplacementRuleId;
    public const string WriteLossApproximateTruncationRuleId = FindingRuleIds.WriteLossApproximateTruncationRuleId;
    public const string WriteLossNumericScaleNarrowingRuleId = FindingRuleIds.WriteLossNumericScaleNarrowingRuleId;
    public const string WriteLossTemporalPrecisionLossRuleId = FindingRuleIds.WriteLossTemporalPrecisionLossRuleId;
    public const string WriteLossLengthTruncationRuleId = FindingRuleIds.WriteLossLengthTruncationRuleId;
    public const string WriteLossTemporalScaleNarrowingRuleId = FindingRuleIds.WriteLossTemporalScaleNarrowingRuleId;
    public const string WriteLossTemporalOffsetDroppedRuleId = FindingRuleIds.WriteLossTemporalOffsetDroppedRuleId;
    public const string TvfFenceCorrelatedApplyRuleId = FindingRuleIds.TvfFenceCorrelatedApplyRuleId;
    public const string TvfFenceNestedUnderViewOrTvfRuleId = FindingRuleIds.TvfFenceNestedUnderViewOrTvfRuleId;
    public const string TvfFenceFromOrJoinRuleId = FindingRuleIds.TvfFenceFromOrJoinRuleId;
    public const string TvfFenceInsertExecRuleId = FindingRuleIds.TvfFenceInsertExecRuleId;
    public const string TvfFenceStandaloneRuleId = FindingRuleIds.TvfFenceStandaloneRuleId;
    public const string ScalarUdfPredicateInvocationRuleId = FindingRuleIds.ScalarUdfPredicateInvocationRuleId;
    public const string ScalarUdfNestedUnderViewOrTvfRuleId = FindingRuleIds.ScalarUdfNestedUnderViewOrTvfRuleId;
    public const string ScalarUdfSchemaDependencyRuleId = FindingRuleIds.ScalarUdfSchemaDependencyRuleId;
    public const string ScalarUdfProjectionInvocationRuleId = FindingRuleIds.ScalarUdfProjectionInvocationRuleId;
    public const string ColumnCollationDriftRuleId = FindingRuleIds.ColumnCollationDriftRuleId;
    public const string ColumnAnsiPaddingOffRuleId = FindingRuleIds.ColumnAnsiPaddingOffRuleId;
    public const string CrossTableTypeDriftRuleId = FindingRuleIds.CrossTableTypeDriftRuleId;
    public const string ProcCallArgumentMismatchRuleId = FindingRuleIds.ProcCallArgumentMismatchRuleId;
    public const string TvfCallArgumentMismatchRuleId = FindingRuleIds.TvfCallArgumentMismatchRuleId;
    public const string ProcCallTableValuedArgumentMismatchRuleId = FindingRuleIds.ProcCallTableValuedArgumentMismatchRuleId;
    public const string SpExecuteSqlParameterMismatchRuleId = FindingRuleIds.SpExecuteSqlParameterMismatchRuleId;
    public const string TemporalBoundaryPrecisionRuleId = FindingRuleIds.TemporalBoundaryPrecisionRuleId;
    public static string MaxTypedColumnRuleId(NonIndexableColumnFindingKind kind) => FindingRuleIds.MaxTypedColumnRuleId(kind);
    public const string ColumnstoreUnsupportedColumnTypeRuleId = FindingRuleIds.ColumnstoreUnsupportedColumnTypeRuleId;
    public static string SelectiveXmlIndexValueColumnRuleId(SelectiveXmlIndexValueColumnFindingKind kind) => FindingRuleIds.SelectiveXmlIndexValueColumnRuleId(kind);
    public static string FullTextIndexDdlRuleId(FullTextIndexDdlFindingKind kind) => FindingRuleIds.FullTextIndexDdlRuleId(kind);
    public static string DynamicDataMaskingRuleId(DynamicDataMaskingFindingKind kind) => FindingRuleIds.DynamicDataMaskingRuleId(kind);
    public const string FloatEqualityRuleId = FindingRuleIds.FloatEqualityRuleId;
    public const string FloatOrderDependentAggregateRuleId = FindingRuleIds.FloatOrderDependentAggregateRuleId;
    public const string AlwaysEncryptedOrderByRuleId = FindingRuleIds.AlwaysEncryptedOrderByRuleId;
    public const string RestrictedImplicitAssignmentRuleId = FindingRuleIds.RestrictedImplicitAssignmentRuleId;
    public const string RevertCookieTypeMismatchRuleId = FindingRuleIds.RevertCookieTypeMismatchRuleId;
    public const string ForXmlExplicitInlineXsdRuleId = FindingRuleIds.ForXmlExplicitInlineXsdRuleId;
    public const string AlwaysEncryptedKeyColumnRuleId = FindingRuleIds.AlwaysEncryptedKeyColumnRuleId;
    public static string AlwaysEncryptedUnsupportedColumnRuleId(AlwaysEncryptedUnsupportedColumnKind kind) => FindingRuleIds.AlwaysEncryptedUnsupportedColumnRuleId(kind);
    public const string TriggerOrderRuleId = FindingRuleIds.TriggerOrderRuleId;
    public static string AlterColumnSafetyRuleId(AlterColumnSafetyKind kind) => FindingRuleIds.AlterColumnSafetyRuleId(kind);
    public static string DropProtectedObjectRuleId(DropProtectedObjectKind kind) => FindingRuleIds.DropProtectedObjectRuleId(kind);
    public static string OnlineRebuildLegacyLobRuleId(OnlineRebuildLegacyLobKind kind) => FindingRuleIds.OnlineRebuildLegacyLobRuleId(kind);
    public static string OperandComparabilityRuleId(OperandComparabilityFindingKind kind) => FindingRuleIds.OperandComparabilityRuleId(kind);
    public const string MemoryOptimizedUnsupportedColumnTypeRuleId = FindingRuleIds.MemoryOptimizedUnsupportedColumnTypeRuleId;
    public const string UnpivotExactTypeMismatchRuleId = FindingRuleIds.UnpivotExactTypeMismatchRuleId;
    public const string SchemaboundAliasTypeRuleId = FindingRuleIds.SchemaboundAliasTypeRuleId;
    public const string SparseColumnDisallowedTypeRuleId = FindingRuleIds.SparseColumnDisallowedTypeRuleId;
    public const string LegacyLobUtf8CollationRuleId = FindingRuleIds.LegacyLobUtf8CollationRuleId;
    public const string MemoryOptimizedUtf8CollationRuleId = FindingRuleIds.MemoryOptimizedUtf8CollationRuleId;
    public const string NativelyCompiledUnsupportedBuiltinRuleId = FindingRuleIds.NativelyCompiledUnsupportedBuiltinRuleId;
    public const string NativelyCompiledClrTypeRuleId = FindingRuleIds.NativelyCompiledClrTypeRuleId;
    public const string NativelyCompiledErrorOutsideCatchRuleId = FindingRuleIds.NativelyCompiledErrorOutsideCatchRuleId;
    public const string NativelyCompiledInterpretedCalleeRuleId = FindingRuleIds.NativelyCompiledInterpretedCalleeRuleId;
    public const string MemoryOptimizedLedgerConflictRuleId = FindingRuleIds.MemoryOptimizedLedgerConflictRuleId;
    public static string MemoryOptimizedUnsupportedIndexOptionRuleId(MemoryOptimizedUnsupportedIndexOptionKind kind) => FindingRuleIds.MemoryOptimizedUnsupportedIndexOptionRuleId(kind);
    public static string MemoryOptimizedForeignKeyRuleId(MemoryOptimizedForeignKeyFindingKind kind) => FindingRuleIds.MemoryOptimizedForeignKeyRuleId(kind);
    public const string MemoryOptimizedSchemaOnlyDurabilityRuleId = FindingRuleIds.MemoryOptimizedSchemaOnlyDurabilityRuleId;
    public const string QueryAntiPatternTableVariableLowCompatEstimateRuleId = FindingRuleIds.QueryAntiPatternTableVariableLowCompatEstimateRuleId;
    public const string QueryAntiPatternTableVariablePspSkipRuleId = FindingRuleIds.QueryAntiPatternTableVariablePspSkipRuleId;
    public const string QueryAntiPatternTableVariableStaleEstimateInLoopRuleId = FindingRuleIds.QueryAntiPatternTableVariableStaleEstimateInLoopRuleId;
    public const string QueryAntiPatternRbarSingleRowLoopDmlRuleId = FindingRuleIds.QueryAntiPatternRbarSingleRowLoopDmlRuleId;
    public const string QueryAntiPatternGlobalCursorDeclarationRuleId = FindingRuleIds.QueryAntiPatternGlobalCursorDeclarationRuleId;
    public const string QueryAntiPatternCountStarVariableExistenceCheckRuleId = FindingRuleIds.QueryAntiPatternCountStarVariableExistenceCheckRuleId;
    public const string QueryAntiPatternNonAggregateHavingPredicateRuleId = FindingRuleIds.QueryAntiPatternNonAggregateHavingPredicateRuleId;
    public const string QueryAntiPatternUnionOfProvablyDisjointBranchesRuleId = FindingRuleIds.QueryAntiPatternUnionOfProvablyDisjointBranchesRuleId;
    public const string QueryAntiPatternDistinctMaskingJoinFanoutRuleId = FindingRuleIds.QueryAntiPatternDistinctMaskingJoinFanoutRuleId;
    public const string QueryAntiPatternUnqualifiedTableReferenceRuleId = FindingRuleIds.QueryAntiPatternUnqualifiedTableReferenceRuleId;
    public const string QueryAntiPatternMergeMissingHoldlockRuleId = FindingRuleIds.QueryAntiPatternMergeMissingHoldlockRuleId;
    public const string QueryAntiPatternMergeNonUniqueUsingSourceRuleId = FindingRuleIds.QueryAntiPatternMergeNonUniqueUsingSourceRuleId;
    public const string QueryAntiPatternMergeUnconditionalDeleteRuleId = FindingRuleIds.QueryAntiPatternMergeUnconditionalDeleteRuleId;
    public const string QueryAntiPatternRecursiveCteMissingMaxRecursionRuleId = FindingRuleIds.QueryAntiPatternRecursiveCteMissingMaxRecursionRuleId;
    public const string QueryAntiPatternUnboundedTableWriteRuleId = FindingRuleIds.QueryAntiPatternUnboundedTableWriteRuleId;
    public const string QueryAntiPatternLinkedServerOrCrossDatabaseReferenceRuleId = FindingRuleIds.QueryAntiPatternLinkedServerOrCrossDatabaseReferenceRuleId;
    public const string QueryAntiPatternMultiRowInsertIgnoreDupKeyDropRuleId = FindingRuleIds.QueryAntiPatternMultiRowInsertIgnoreDupKeyDropRuleId;
    public const string QueryAntiPatternAlterTableSwitchColumnMismatchRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchColumnMismatchRuleId;
    public const string QueryAntiPatternAlterTableSwitchIndexMismatchRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchIndexMismatchRuleId;
    public const string QueryAntiPatternAlterTableSwitchConstraintMismatchRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchConstraintMismatchRuleId;
    public const string QueryAntiPatternAlterTableSwitchTargetOnlyIndexRestrictionRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchTargetOnlyIndexRestrictionRuleId;
    public const string QueryAntiPatternAlterTableSwitchFilegroupMismatchRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchFilegroupMismatchRuleId;
    public const string QueryAntiPatternAlterTableSwitchTemporalMismatchRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchTemporalMismatchRuleId;
    public const string QueryAntiPatternAlterTableSwitchRuleConstraintRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchRuleConstraintRuleId;
    public const string QueryAntiPatternAlterTableSwitchCdcPartitionSwitchRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchCdcPartitionSwitchRuleId;
    public const string QueryAntiPatternAlterTableSwitchPartitionFilegroupMismatchRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchPartitionFilegroupMismatchRuleId;
    public const string QueryAntiPatternAlterTableSwitchFullTextIndexRestrictionRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchFullTextIndexRestrictionRuleId;
    public const string QueryAntiPatternAlterTableSwitchIndexedViewAlignmentRuleId = FindingRuleIds.QueryAntiPatternAlterTableSwitchIndexedViewAlignmentRuleId;
    public const string QueryAntiPatternAlterSchemaTransferMsShippedObjectRuleId = FindingRuleIds.QueryAntiPatternAlterSchemaTransferMsShippedObjectRuleId;
    public const string QueryAntiPatternGroupingSetsCardinalityLimitExceededRuleId = FindingRuleIds.QueryAntiPatternGroupingSetsCardinalityLimitExceededRuleId;
    public const string QueryAntiPatternGroupingArgumentNotInGroupByListRuleId = FindingRuleIds.QueryAntiPatternGroupingArgumentNotInGroupByListRuleId;
    public const string QueryAntiPatternAlterTableRebuildPartitionOutOfRangeRuleId = FindingRuleIds.QueryAntiPatternAlterTableRebuildPartitionOutOfRangeRuleId;
    public const string QueryAntiPatternPartitionRebuildNumberExceedsCeilingRuleId = FindingRuleIds.QueryAntiPatternPartitionRebuildNumberExceedsCeilingRuleId;
    public const string IndexCoverageKeyLookupProneIndexRuleId = FindingRuleIds.IndexCoverageKeyLookupProneIndexRuleId;
    public const string TriggerCorrectnessMultiRowUnsafeSingleRowAssignmentRuleId = FindingRuleIds.TriggerCorrectnessMultiRowUnsafeSingleRowAssignmentRuleId;
    public const string TriggerCorrectnessMultiRowUnsafeKeyedDmlRuleId = FindingRuleIds.TriggerCorrectnessMultiRowUnsafeKeyedDmlRuleId;
    public const string TriggerCorrectnessNoEarlyOutForEmptyInvocationRuleId = FindingRuleIds.TriggerCorrectnessNoEarlyOutForEmptyInvocationRuleId;
    public const string TriggerCorrectnessDirectRecursiveTriggerRuleId = FindingRuleIds.TriggerCorrectnessDirectRecursiveTriggerRuleId;
    public const string TriggerCorrectnessInsteadOfInsertFilteredNoRejectPathRuleId = FindingRuleIds.TriggerCorrectnessInsteadOfInsertFilteredNoRejectPathRuleId;
    public const string TriggerCorrectnessUpdateFunctionWithoutValueComparisonRuleId = FindingRuleIds.TriggerCorrectnessUpdateFunctionWithoutValueComparisonRuleId;
    public const string TriggerCorrectnessLogonTriggerHostNameGateRuleId = FindingRuleIds.TriggerCorrectnessLogonTriggerHostNameGateRuleId;
    public const string CrossModuleLockOrderRuleId = FindingRuleIds.CrossModuleLockOrderRuleId;
    public const string TriggerRecursionCycleRuleId = FindingRuleIds.TriggerRecursionCycleRuleId;
    public const string OversizedParameterRuleId = FindingRuleIds.OversizedParameterRuleId;
    public const string UnderLengthParameterRuleId = FindingRuleIds.UnderLengthParameterRuleId;
    public const string AnsiPaddingMismatchRuleId = FindingRuleIds.AnsiPaddingMismatchRuleId;
    public const string CatchAllPredicateRuleId = FindingRuleIds.CatchAllPredicateRuleId;
    public const string LocalVariablePredicateRuleId = FindingRuleIds.LocalVariablePredicateRuleId;
    public const string FilteredIndexParameterMismatchRuleId = FindingRuleIds.FilteredIndexParameterMismatchRuleId;
    public const string ParameterReassignmentPredicateRuleId = FindingRuleIds.ParameterReassignmentPredicateRuleId;
    public const string CodeMetricLineTooLongRuleId = FindingRuleIds.CodeMetricLineTooLongRuleId;
    public const string CodeMetricModuleTooLongRuleId = FindingRuleIds.CodeMetricModuleTooLongRuleId;
    public const string CodeMetricRoutineTooLongRuleId = FindingRuleIds.CodeMetricRoutineTooLongRuleId;
    public const string CodeMetricTooManyParametersRuleId = FindingRuleIds.CodeMetricTooManyParametersRuleId;
    public const string CodeMetricNestingTooDeepRuleId = FindingRuleIds.CodeMetricNestingTooDeepRuleId;
    public const string CodeMetricTooManyConditionalOperatorsRuleId = FindingRuleIds.CodeMetricTooManyConditionalOperatorsRuleId;
    public const string CodeMetricTooManyCaseBranchesRuleId = FindingRuleIds.CodeMetricTooManyCaseBranchesRuleId;
    public const string CodeMetricCaseBranchTooLongRuleId = FindingRuleIds.CodeMetricCaseBranchTooLongRuleId;
    public const string FormattingTabCharacterUsedRuleId = FindingRuleIds.FormattingTabCharacterUsedRuleId;
    public const string FormattingMultipleStatementsOnSameLineRuleId = FindingRuleIds.FormattingMultipleStatementsOnSameLineRuleId;
    public const string FormattingMultipleDeclarationsOnSameLineRuleId = FindingRuleIds.FormattingMultipleDeclarationsOnSameLineRuleId;
    public const string FormattingMissingBeginEndBlockRuleId = FindingRuleIds.FormattingMissingBeginEndBlockRuleId;
    public const string FormattingSingleLineConditionalBodyRuleId = FindingRuleIds.FormattingSingleLineConditionalBodyRuleId;
    public const string FormattingDanglingStatementAfterUnbracedBodyRuleId = FindingRuleIds.FormattingDanglingStatementAfterUnbracedBodyRuleId;
    public const string FormattingIfImmediatelyFollowingPriorBlockEndRuleId = FindingRuleIds.FormattingIfImmediatelyFollowingPriorBlockEndRuleId;
    public const string FormattingRedundantParenthesesRuleId = FindingRuleIds.FormattingRedundantParenthesesRuleId;
    public const string FormattingMissingFileHeaderCommentRuleId = FindingRuleIds.FormattingMissingFileHeaderCommentRuleId;
    public const string NamingReservedKeywordAsIdentifierRuleId = FindingRuleIds.NamingReservedKeywordAsIdentifierRuleId;
    public const string NamingSpPrefixOnUserRoutineRuleId = FindingRuleIds.NamingSpPrefixOnUserRoutineRuleId;
    public const string NamingUnqualifiedCreateRuleId = FindingRuleIds.NamingUnqualifiedCreateRuleId;
    public const string NamingRedundantTypeQualifierRuleId = FindingRuleIds.NamingRedundantTypeQualifierRuleId;
    public const string DeadCodeUnreachableCodeRuleId = FindingRuleIds.DeadCodeUnreachableCodeRuleId;
    public const string DeadCodeUnusedLabelRuleId = FindingRuleIds.DeadCodeUnusedLabelRuleId;
    public const string DeadCodeUnusedLocalVariableRuleId = FindingRuleIds.DeadCodeUnusedLocalVariableRuleId;
    public const string DeadCodeUnusedParameterRuleId = FindingRuleIds.DeadCodeUnusedParameterRuleId;
    public const string DeadCodeRedundantJumpRuleId = FindingRuleIds.DeadCodeRedundantJumpRuleId;
    public const string DuplicationCommentedOutCodeRuleId = FindingRuleIds.DuplicationCommentedOutCodeRuleId;
    public const string DuplicationDuplicatedStringLiteralRuleId = FindingRuleIds.DuplicationDuplicatedStringLiteralRuleId;
    public const string DuplicationSingleIterationLoopRuleId = FindingRuleIds.DuplicationSingleIterationLoopRuleId;
    public const string DuplicationSelfAssignmentRuleId = FindingRuleIds.DuplicationSelfAssignmentRuleId;
    public const string DuplicationIdenticalBinaryOperandsRuleId = FindingRuleIds.DuplicationIdenticalBinaryOperandsRuleId;
    public const string DuplicationRepeatedUnaryOperatorRuleId = FindingRuleIds.DuplicationRepeatedUnaryOperatorRuleId;
    public const string DuplicationNegatedComparisonAsOppositeRuleId = FindingRuleIds.DuplicationNegatedComparisonAsOppositeRuleId;
    public const string DuplicationDuplicateSiblingConditionRuleId = FindingRuleIds.DuplicationDuplicateSiblingConditionRuleId;
    public const string DuplicationIdenticalBranchBodiesRuleId = FindingRuleIds.DuplicationIdenticalBranchBodiesRuleId;
    public const string DuplicationAllBranchesIdenticalRuleId = FindingRuleIds.DuplicationAllBranchesIdenticalRuleId;
    public const string DuplicationRedundantAndConditionRuleId = FindingRuleIds.DuplicationRedundantAndConditionRuleId;
    public const string DuplicationMutuallyExclusiveAndConditionRuleId = FindingRuleIds.DuplicationMutuallyExclusiveAndConditionRuleId;
    public const string DuplicationCollapsibleNestedIfRuleId = FindingRuleIds.DuplicationCollapsibleNestedIfRuleId;
    public const string DuplicationNestedConditionalExpressionRuleId = FindingRuleIds.DuplicationNestedConditionalExpressionRuleId;
    public const string DuplicationAlwaysTrueOrFalseLiteralComparisonRuleId = FindingRuleIds.DuplicationAlwaysTrueOrFalseLiteralComparisonRuleId;
    public const string DeprecatedSyntaxTaskCommentTodoRuleId = FindingRuleIds.DeprecatedSyntaxTaskCommentTodoRuleId;
    public const string DeprecatedSyntaxTaskCommentFixmeRuleId = FindingRuleIds.DeprecatedSyntaxTaskCommentFixmeRuleId;
    public const string DeprecatedSyntaxNonAnsiComparisonOperatorRuleId = FindingRuleIds.DeprecatedSyntaxNonAnsiComparisonOperatorRuleId;
    public const string DeprecatedSyntaxEqualsNullComparisonRuleId = FindingRuleIds.DeprecatedSyntaxEqualsNullComparisonRuleId;
    public const string DeprecatedSyntaxNotEqualsNullComparisonRuleId = FindingRuleIds.DeprecatedSyntaxNotEqualsNullComparisonRuleId;
    public const string DeprecatedSyntaxLikeWithNoWildcardRuleId = FindingRuleIds.DeprecatedSyntaxLikeWithNoWildcardRuleId;
    public const string DeprecatedSyntaxLegacySystemCompatibilityViewRuleId = FindingRuleIds.DeprecatedSyntaxLegacySystemCompatibilityViewRuleId;
    public const string DeprecatedSyntaxTableHintWithoutWithRuleId = FindingRuleIds.DeprecatedSyntaxTableHintWithoutWithRuleId;
    public const string DeprecatedSyntaxNumberedProcedureDefinitionRuleId = FindingRuleIds.DeprecatedSyntaxNumberedProcedureDefinitionRuleId;
    public const string DeprecatedSyntaxNumberedProcedureExecutionRuleId = FindingRuleIds.DeprecatedSyntaxNumberedProcedureExecutionRuleId;
    public const string DeprecatedSyntaxStringLiteralColumnAliasRuleId = FindingRuleIds.DeprecatedSyntaxStringLiteralColumnAliasRuleId;
    public const string DeprecatedSyntaxRemovedSecurityStoredProcedureRuleId = FindingRuleIds.DeprecatedSyntaxRemovedSecurityStoredProcedureRuleId;
    public const string DeprecatedSyntaxDeprecatedSetRowcountRuleId = FindingRuleIds.DeprecatedSyntaxDeprecatedSetRowcountRuleId;
    public const string DeprecatedSyntaxLegacyLobStatementRuleId = FindingRuleIds.DeprecatedSyntaxLegacyLobStatementRuleId;
    public const string DeprecatedSyntaxLegacyLobFunctionRuleId = FindingRuleIds.DeprecatedSyntaxLegacyLobFunctionRuleId;
    public const string StatementShapeInsertWithoutColumnListRuleId = FindingRuleIds.StatementShapeInsertWithoutColumnListRuleId;
    public const string StatementShapeOrdinalOrderByRuleId = FindingRuleIds.StatementShapeOrdinalOrderByRuleId;
    public const string StatementShapeTableWithNoPrimaryKeyRuleId = FindingRuleIds.StatementShapeTableWithNoPrimaryKeyRuleId;
    public const string StatementShapeMissingSetNocountOnRuleId = FindingRuleIds.StatementShapeMissingSetNocountOnRuleId;
    public const string StatementShapeBareSelectStarRuleId = FindingRuleIds.StatementShapeBareSelectStarRuleId;
    public const string ControlFlowRiskCursorFetchColumnCountMismatchRuleId = FindingRuleIds.ControlFlowRiskCursorFetchColumnCountMismatchRuleId;
    public const string ControlFlowRiskEmptyCatchBlockRuleId = FindingRuleIds.ControlFlowRiskEmptyCatchBlockRuleId;
    public const string ControlFlowRiskTriggerEmitsOutputRuleId = FindingRuleIds.ControlFlowRiskTriggerEmitsOutputRuleId;
    public const string ControlFlowRiskDirtyReadIsolationHintRuleId = FindingRuleIds.ControlFlowRiskDirtyReadIsolationHintRuleId;
    public const string ControlFlowRiskReadCommittedLockRevertsRowVersioningRuleId = FindingRuleIds.ControlFlowRiskReadCommittedLockRevertsRowVersioningRuleId;
    public const string ControlFlowRiskDuplicatedCallArgumentRuleId = FindingRuleIds.ControlFlowRiskDuplicatedCallArgumentRuleId;
    public const string ControlFlowRiskLegacyIdentityIntrinsicRuleId = FindingRuleIds.ControlFlowRiskLegacyIdentityIntrinsicRuleId;
    public const string ControlFlowRiskGotoUsageRuleId = FindingRuleIds.ControlFlowRiskGotoUsageRuleId;
    public const string ControlFlowRiskCaseExpressionMissingElseRuleId = FindingRuleIds.ControlFlowRiskCaseExpressionMissingElseRuleId;
    public const string ControlFlowRiskNonDeterministicCaseInputRuleId = FindingRuleIds.ControlFlowRiskNonDeterministicCaseInputRuleId;
    public const string NotInNullableSubqueryRuleId = FindingRuleIds.NotInNullableSubqueryRuleId;
    public const string NonUniqueUpdateSourceRuleId = FindingRuleIds.NonUniqueUpdateSourceRuleId;
    public const string CheckConstraintPredicateContradictionIntervalRuleId = FindingRuleIds.CheckConstraintPredicateContradictionIntervalRuleId;
    public const string NotNullPredicateContradictionRuleId = FindingRuleIds.NotNullPredicateContradictionRuleId;
    public static string CheckConstraintPredicateContradictionRuleId(CheckConstraintPredicateContradictionKind kind) => FindingRuleIds.CheckConstraintPredicateContradictionRuleId(kind);
    public static string GeneratedAlwaysColumnAssignmentRuleId(GeneratedAlwaysColumnAssignmentKind kind) => FindingRuleIds.GeneratedAlwaysColumnAssignmentRuleId(kind);
    public const string ForcedSerialTableVariableModificationRuleId = FindingRuleIds.ForcedSerialTableVariableModificationRuleId;
    public const string ForcedSerialFastForwardCursorRuleId = FindingRuleIds.ForcedSerialFastForwardCursorRuleId;
    public const string ForcedSerialNonParallelizableIntrinsicRuleId = FindingRuleIds.ForcedSerialNonParallelizableIntrinsicRuleId;
    public const string UntrustedForeignKeyRuleId = FindingRuleIds.UntrustedForeignKeyRuleId;
    public const string UntrustedCheckConstraintRuleId = FindingRuleIds.UntrustedCheckConstraintRuleId;
    public const string CascadingForeignKeyRuleId = FindingRuleIds.CascadingForeignKeyRuleId;
    public const string MultiReferencedCteRuleId = FindingRuleIds.MultiReferencedCteRuleId;
    public const string RecursiveCteAnchorTypeMismatchRuleId = FindingRuleIds.RecursiveCteAnchorTypeMismatchRuleId;
    public const string NestedViewDepthRuleId = FindingRuleIds.NestedViewDepthRuleId;
    public const string PostExpansionJoinWidthRuleId = FindingRuleIds.PostExpansionJoinWidthRuleId;
    public const string SelectStarViewRuleId = FindingRuleIds.SelectStarViewRuleId;
    public const string PartialCompositeForeignKeyJoinRuleId = FindingRuleIds.PartialCompositeForeignKeyJoinRuleId;
    public const string OuterJoinPredicateCollapseRuleId = FindingRuleIds.OuterJoinPredicateCollapseRuleId;
    public const string ConcatenatedValueInConstantSqlRuleId = FindingRuleIds.ConcatenatedValueInConstantSqlRuleId;
    public const string ExecStringConcatenatesParameterizableValueRuleId = FindingRuleIds.ExecStringConcatenatesParameterizableValueRuleId;
    public const string TempTableExecShapeColumnCountMismatchRuleId = FindingRuleIds.TempTableExecShapeColumnCountMismatchRuleId;
    public const string TempTableExecShapeColumnTypeMismatchRuleId = FindingRuleIds.TempTableExecShapeColumnTypeMismatchRuleId;
    public const string ExecResultSetsShapeColumnCountMismatchRuleId = FindingRuleIds.ExecResultSetsShapeColumnCountMismatchRuleId;
    public const string ExecResultSetsShapeColumnTypeMismatchRuleId = FindingRuleIds.ExecResultSetsShapeColumnTypeMismatchRuleId;
    public const string NonPersistedComputedColumnRuleId = FindingRuleIds.NonPersistedComputedColumnRuleId;
    public const string SelfReferencingDmlRuleId = FindingRuleIds.SelfReferencingDmlRuleId;
    public const string TemporalTableHistoryIndexGapRuleId = FindingRuleIds.TemporalTableHistoryIndexGapRuleId;
    public const string CheckConstraintNullNotHandledRuleId = FindingRuleIds.CheckConstraintNullNotHandledRuleId;
    public const string CheckConstraintOnIdentityColumnRuleId = FindingRuleIds.CheckConstraintOnIdentityColumnRuleId;
    public const string DefaultNullableConstraintRuleId = FindingRuleIds.DefaultNullableConstraintRuleId;
    public const string TryCastComputedColumnPredicateRuleId = FindingRuleIds.TryCastComputedColumnPredicateRuleId;
    public const string StaleSelectStarViewRuleId = FindingRuleIds.StaleSelectStarViewRuleId;
    public const string BareTopNoOrderByRuleId = FindingRuleIds.BareTopNoOrderByRuleId;
    public const string StringConcatNullRuleId = FindingRuleIds.StringConcatNullRuleId;
    public const string AggregateDivisionColumnstoreRuleId = FindingRuleIds.AggregateDivisionColumnstoreRuleId;
    public const string SecurityPredicateIndexRuleId = FindingRuleIds.SecurityPredicateIndexRuleId;
    public const string DanglingObjectReferenceRuleId = FindingRuleIds.DanglingObjectReferenceRuleId;
    public static string ModuleCompileFlagRuleId(ModuleCompileFlagFindingKind kind) => FindingRuleIds.ModuleCompileFlagRuleId(kind);
    public static string WindowFrameRuleId(WindowFrameFindingKind kind) => FindingRuleIds.WindowFrameRuleId(kind);
    public static string WindowFunctionArgumentRuleId(WindowFunctionArgumentFindingKind kind) => FindingRuleIds.WindowFunctionArgumentRuleId(kind);
    public static string StringSplitArgumentRuleId(StringSplitArgumentFindingKind kind) => FindingRuleIds.StringSplitArgumentRuleId(kind);
    public static string BoundedStringBuiltinTruncationRuleId(BoundedStringBuiltinTruncationFindingKind kind) => FindingRuleIds.BoundedStringBuiltinTruncationRuleId(kind);
    public const string WaitForRuleId = FindingRuleIds.WaitForRuleId;
    public const string BackupOptionConflictRuleId = FindingRuleIds.BackupOptionConflictRuleId;
    public const string RestoreOptionConflictRuleId = FindingRuleIds.RestoreOptionConflictRuleId;
    public const string CreateDatabaseOptionConflictRuleId = FindingRuleIds.CreateDatabaseOptionConflictRuleId;
    public const string ViewCheckOptionContradictionRuleId = FindingRuleIds.ViewCheckOptionContradictionRuleId;
    public const string GraphPseudoColumnAssignmentRuleId = FindingRuleIds.GraphPseudoColumnAssignmentRuleId;
    public const string CursorCloseOnCommitRuleId = FindingRuleIds.CursorCloseOnCommitRuleId;
    public static string TransactionHygieneRuleId(TransactionHygieneFindingKind kind) => FindingRuleIds.TransactionHygieneRuleId(kind);
    public const string OutputParameterRuleId = FindingRuleIds.OutputParameterRuleId;
    public const string CompositeIndexLeadingColumnRuleId = FindingRuleIds.CompositeIndexLeadingColumnRuleId;
    public const string MissingStatisticsRuleId = FindingRuleIds.MissingStatisticsRuleId;
    public static string IndexHintRuleId(IndexHintFindingKind kind) => FindingRuleIds.IndexHintRuleId(kind);
    public static string SessionDateSettingRuleId(SessionDateSettingKind kind) => FindingRuleIds.SessionDateSettingRuleId(kind);
    public const string AmbiguousDateLiteralConversionRuleId = FindingRuleIds.AmbiguousDateLiteralConversionRuleId;
    public static string CartesianJoinRuleId(CartesianJoinKind kind) => FindingRuleIds.CartesianJoinRuleId(kind);
    public const string TruncateSwallowedRuleId = FindingRuleIds.TruncateSwallowedRuleId;
    public static string DatabaseConfigurationRuleId(DatabaseConfigurationFindingKind kind) => FindingRuleIds.DatabaseConfigurationRuleId(kind);
    public static string UnindexedTempTableUsageRuleId(UnindexedTempTableUsageKind kind) => FindingRuleIds.UnindexedTempTableUsageRuleId(kind);
    public static string SecurityRuleId(SecurityFindingKind kind) => FindingRuleIds.SecurityRuleId(kind);
    public static string ViewOrderingRuleId(ViewOrderingFindingKind kind) => FindingRuleIds.ViewOrderingRuleId(kind);
    public static string IndexDesignRuleId(IndexDesignFindingKind kind) => FindingRuleIds.IndexDesignRuleId(kind);
    public static string ForcedParameterizationRuleId(ForcedParameterizationFindingKind kind) => FindingRuleIds.ForcedParameterizationRuleId(kind);
    public static string IdentityRangeRuleId(IdentityRangeFindingKind kind) => FindingRuleIds.IdentityRangeRuleId(kind);
    public static string SetOptionRuleId(SetOptionFindingKind kind) => FindingRuleIds.SetOptionRuleId(kind);
    public static string UnparameterizedDynamicSqlRuleId(UnparameterizedDynamicSqlFindingKind kind) => FindingRuleIds.UnparameterizedDynamicSqlRuleId(kind);
    public static string TempTableExecShapeRuleId(TempTableExecShapeFindingKind kind) => FindingRuleIds.TempTableExecShapeRuleId(kind);
    public static string ExecResultSetsShapeRuleId(ExecResultSetsShapeFindingKind kind) => FindingRuleIds.ExecResultSetsShapeRuleId(kind);
    public static string ForcedSerialRuleId(ForcedSerialFindingKind kind) => FindingRuleIds.ForcedSerialRuleId(kind);
    public static string CodeMetricRuleId(CodeMetricFindingKind kind) => FindingRuleIds.CodeMetricRuleId(kind);
    public static string FormattingRuleId(FormattingFindingKind kind) => FindingRuleIds.FormattingRuleId(kind);
    public static string NamingRuleId(NamingFindingKind kind) => FindingRuleIds.NamingRuleId(kind);
    public static string DeadCodeRuleId(DeadCodeFindingKind kind) => FindingRuleIds.DeadCodeRuleId(kind);
    public static string DuplicationRuleId(DuplicationFindingKind kind) => FindingRuleIds.DuplicationRuleId(kind);
    public static string DeprecatedSyntaxRuleId(DeprecatedSyntaxFindingKind kind) => FindingRuleIds.DeprecatedSyntaxRuleId(kind);
    public static string StatementShapeRuleId(StatementShapeFindingKind kind) => FindingRuleIds.StatementShapeRuleId(kind);
    public static string ControlFlowRiskRuleId(ControlFlowRiskFindingKind kind) => FindingRuleIds.ControlFlowRiskRuleId(kind);
    public static string QueryAntiPatternRuleId(QueryAntiPatternFindingKind kind) => FindingRuleIds.QueryAntiPatternRuleId(kind);
    public static string IndexCoverageRuleId(IndexCoverageFindingKind kind) => FindingRuleIds.IndexCoverageRuleId(kind);
    public static string TriggerCorrectnessRuleId(TriggerCorrectnessFindingKind kind) => FindingRuleIds.TriggerCorrectnessRuleId(kind);
    public static string UntrustedConstraintRuleId(UntrustedConstraintFindingKind kind) => FindingRuleIds.UntrustedConstraintRuleId(kind);
    public static string CheckConstraintRuleId(CheckConstraintFindingKind kind) => FindingRuleIds.CheckConstraintRuleId(kind);
    public static string TvfFenceRuleId(TvfFenceFindingKind kind) => FindingRuleIds.TvfFenceRuleId(kind);
    public static string ScalarUdfRuleId(ScalarUdfFindingKind kind) => FindingRuleIds.ScalarUdfRuleId(kind);
    public static string WriteLossRuleId(WriteLossKind kind) => FindingRuleIds.WriteLossRuleId(kind);
    public static string DynamicSqlRuleId(DynamicSqlOutcome outcome) => FindingRuleIds.DynamicSqlRuleId(outcome);
    public static string Tier1RuleId(SargabilityFindingKind kind) => FindingRuleIds.Tier1RuleId(kind);
    public static string VerdictRuleId(Verdict verdict) => FindingRuleIds.VerdictRuleId(verdict);

    private static readonly HashSet<string> DynamicSqlOutcomeRuleIds = new(StringComparer.Ordinal)
    {
        DynamicSqlAnalyzedRuleId,
        DynamicSqlUnanalyzableRuleId,
        DynamicSqlInnerParseFailedRuleId,
        DynamicSqlPartiallyAnalyzedRuleId,
    };

    public static string RuleId(string baseRuleId, FindingConfidence confidence) => confidence switch
    {
        FindingConfidence.High => baseRuleId,
        FindingConfidence.Medium => $"{baseRuleId}/medium-confidence",
        FindingConfidence.Low => $"{baseRuleId}/low-confidence",
        _ => throw new ArgumentOutOfRangeException(nameof(confidence), confidence, "Unhandled FindingConfidence."),
    };

    public static IReadOnlyList<SarifRule> AllRules { get; } = BuildAllRules();

    private static IReadOnlyList<SarifRule> BuildAllRules()
    {
        var baseRules = RuleCatalog.BaseRules.Select(rule => Rule(rule.Id, rule.Rationale)).ToArray();

        var mediumVariants = baseRules
            .Where(rule => !DynamicSqlOutcomeRuleIds.Contains(rule.Id))
            .Select(rule => Rule(RuleId(rule.Id, FindingConfidence.Medium), $"(Medium confidence) {rule.ShortDescription.Text}"));
        var lowVariants = baseRules
            .Where(rule => !DynamicSqlOutcomeRuleIds.Contains(rule.Id))
            .Select(rule => Rule(RuleId(rule.Id, FindingConfidence.Low), $"(Low confidence) {rule.ShortDescription.Text}"));

        return [.. baseRules, .. mediumVariants, .. lowVariants];
    }

    private static SarifRule Rule(string id, string description) => new(id, new SarifMessage(description), RuleDocSite.Url(id));
}
