using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using SilentScan.Core.Catalog;
using SilentScan.Core.TypeInference;

namespace SilentScan.Core.Rules;

/// <summary>
/// The checked-in, oracle-probed replacement for a hand-written "these type categories are
/// widening-compatible" heuristic (CLAUDE.md precision discipline: verify against our Docker
/// oracle, don't blindly trust either source). Loaded once from the embedded
/// <c>Rules/TypePairMatrix.json</c> resource generated by
/// <c>silentscan-verify generate-type-matrix</c>.
/// A pair with no recorded probe returns null from <see cref="TryGetOutcome"/> - the classifier
/// must treat that as UNKNOWN, never fall back to guessing from the precedence list alone.
/// </summary>
public sealed class TypePairMatrix
{
    public static TypePairMatrix Instance { get; } = LoadEmbedded();

    private readonly Dictionary<(SqlTypeCategory Column, SqlTypeCategory Other, string? Collation), TypePairOutcome> _byKey;

    public string ServerVersion { get; }

    public string ProbedAtUtc { get; }

    public IReadOnlyList<TypePairOutcome> Entries { get; }

    internal TypePairMatrix(string serverVersion, string probedAtUtc, IReadOnlyList<TypePairOutcome> entries)
    {
        ServerVersion = serverVersion;
        ProbedAtUtc = probedAtUtc;
        Entries = entries;
        _byKey = entries.ToDictionary(e => (e.ColumnCategory, e.OtherCategory, e.CollationName));
    }

    /// <summary>
    /// Looks up the probed outcome for a column of <paramref name="columnCategory"/> compared
    /// against <paramref name="otherCategory"/>. For a string-family pair, pass the column's
    /// effective collation name; a probe recorded for a different collation is not reused for
    /// another - collation is comparison-relevant, not incidental. Returns null if this exact
    /// cell was never probed.
    /// </summary>
    public TypePairOutcome? TryGetOutcome(SqlTypeCategory columnCategory, SqlTypeCategory otherCategory, string? collationName = null) =>
        _byKey.TryGetValue((columnCategory, otherCategory, collationName), out var outcome) ? outcome : null;

    /// <summary>
    /// For a string-family column whose own collation is unresolved: some category pairs
    /// (e.g. nvarchar column vs varchar value) never convert the column regardless of which
    /// collation is in play - that's a precedence-direction fact, not a collation-dependent
    /// one, verified empirically by every probed collation variant of the pair agreeing. This
    /// is NOT a guess - it only returns a result when every collation this matrix ever probed
    /// for the pair reached the identical outcome; a pair where collation genuinely changes the
    /// answer (varchar column vs nvarchar value - ScanForced under SQL_*, RangeSeek under
    /// Windows) returns null here exactly as it should, forcing the caller to fall back to
    /// UNKNOWN rather than pick one collation's answer arbitrarily.
    /// </summary>
    public TypePairOutcome? TryGetOutcomeAgreeingAcrossCollations(SqlTypeCategory columnCategory, SqlTypeCategory otherCategory)
    {
        var variants = Entries.Where(e => e.ColumnCategory == columnCategory && e.OtherCategory == otherCategory && e.CollationName is not null).ToList();
        return TryGetAgreeingOutcome(variants);
    }

    /// <summary>
    /// For a string-family column whose collation IS resolved, but not to one of the exact
    /// names this matrix ever probed (e.g. a real corpus using
    /// <c>SQL_Latin1_General_CP1_CS_AS</c> when only the case-insensitive variant was probed):
    /// falls back to every probed collation that shares the SAME family
    /// (<see cref="Collation.IsSqlFamily"/> - SQL_* vs Windows/UTF8/BIN2, the actual axis
    /// CLAUDE.md's type rules turn on), and only returns a result when all of THAT family's
    /// probed representatives agree - the same "never guess, only generalize a unanimous
    /// finding" discipline <see cref="TryGetOutcomeAgreeingAcrossCollations"/> already applies
    /// across every collation. A resolved collation must never carry LESS information than an
    /// unresolved one: this family-scoped agreement set is a subset of that method's
    /// all-collations set, so whenever the all-collations check would succeed, this one does
    /// too (a unanimous full set is unanimous on every subset) - and it additionally succeeds in
    /// cases the all-collations check cannot, when only this collation's own family agrees.
    /// Never invoked for a pair this matrix has no probe data for at all (an out-of-model
    /// category, or a category pair never probed) - that stays "no-probed-matrix-cell" Unknown.
    /// </summary>
    public TypePairOutcome? TryGetOutcomeAgreeingWithinFamily(SqlTypeCategory columnCategory, SqlTypeCategory otherCategory, bool isSqlFamily)
    {
        var variants = Entries.Where(e =>
            e.ColumnCategory == columnCategory
            && e.OtherCategory == otherCategory
            && e.CollationName is not null
            && new Collation(e.CollationName).IsSqlFamily == isSqlFamily).ToList();
        return TryGetAgreeingOutcome(variants);
    }

    /// <summary>
    /// Resolved-collation lookup that never regresses below what an unresolved collation would
    /// get: tries the exact probed cell first, then falls back to
    /// <see cref="TryGetOutcomeAgreeingWithinFamily"/>. Pass <paramref name="collation"/> as null
    /// for an unresolved column collation - that routes to <see cref="TryGetOutcomeAgreeingAcrossCollations"/>
    /// instead, exactly as before this method existed.
    /// </summary>
    public TypePairOutcome? TryGetOutcomeForColumnCollation(SqlTypeCategory columnCategory, SqlTypeCategory otherCategory, Collation? collation)
    {
        if (collation is null)
        {
            return TryGetOutcomeAgreeingAcrossCollations(columnCategory, otherCategory);
        }

        return TryGetOutcome(columnCategory, otherCategory, collation.Name)
            ?? TryGetOutcomeAgreeingWithinFamily(columnCategory, otherCategory, collation.IsSqlFamily);
    }

    private static TypePairOutcome? TryGetAgreeingOutcome(List<TypePairOutcome> variants)
    {
        if (variants.Count == 0)
        {
            return null;
        }

        var first = variants[0];
        var allAgree = variants.All(v => v.CompileFailed == first.CompileFailed
            && v.ColumnConverts == first.ColumnConverts
            && v.DynamicRangeSeekAvailable == first.DynamicRangeSeekAvailable);

        return allAgree ? first with { CollationName = null } : null;
    }

    private static TypePairMatrix LoadEmbedded()
    {
        var assembly = typeof(TypePairMatrix).Assembly;
        var resourceName = $"{assembly.GetName().Name}.Rules.TypePairMatrix.json";
        using var stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{resourceName}' not found - the matrix data is missing from the build.");

        var document = JsonSerializer.Deserialize<MatrixDocument>(stream, JsonOptions)
            ?? throw new InvalidOperationException("TypePairMatrix.json deserialized to null.");

        var entries = document.Entries.Select(e => new TypePairOutcome(
            Enum.Parse<SqlTypeCategory>(e.ColumnCategory),
            Enum.Parse<SqlTypeCategory>(e.OtherCategory),
            e.CollationName,
            e.ColumnConverts,
            e.CompileFailed,
            e.DynamicRangeSeekAvailable)).ToList();

        return new TypePairMatrix(document.ServerVersion, document.ProbedAtUtc, entries);
    }

    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };

    private sealed record MatrixDocument(
        [property: JsonPropertyName("ServerVersion")] string ServerVersion,
        [property: JsonPropertyName("ProbedAtUtc")] string ProbedAtUtc,
        [property: JsonPropertyName("Notes")] string Notes,
        [property: JsonPropertyName("Entries")] IReadOnlyList<MatrixEntryDocument> Entries);

    private sealed record MatrixEntryDocument(
        string ColumnCategory,
        string OtherCategory,
        string? CollationName,
        bool ColumnConverts,
        bool CompileFailed,
        bool DynamicRangeSeekAvailable);
}
