using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using SilentScan.Core.Catalog;

namespace SilentScan.Core.Rules;

/// <summary>
/// The checked-in, oracle-probed replacement for a hand-written "these type categories are
/// widening-compatible" heuristic (CLAUDE.md precision discipline: verify against our Docker
/// oracle, don't blindly trust either source). Loaded once from the embedded
/// <c>Rules/TypePairMatrix.json</c> resource generated by
/// <c>silentscan-verify generate-type-matrix</c>.
/// A pair with no recorded probe returns null from <see cref="TryGetOutcome"/> - the classifier
/// must treat that as UNKNOWN, never fall back to guessing from the precedence list alone.
/// </summary>
public sealed class TypePairMatrix
{
    public static TypePairMatrix Instance { get; } = LoadEmbedded();

    private readonly Dictionary<(SqlTypeCategory Column, SqlTypeCategory Other, string? Collation), TypePairOutcome> _byKey;

    public string ServerVersion { get; }

    public string ProbedAtUtc { get; }

    public IReadOnlyList<TypePairOutcome> Entries { get; }

    internal TypePairMatrix(string serverVersion, string probedAtUtc, IReadOnlyList<TypePairOutcome> entries)
    {
        ServerVersion = serverVersion;
        ProbedAtUtc = probedAtUtc;
        Entries = entries;
        _byKey = entries.ToDictionary(e => (e.ColumnCategory, e.OtherCategory, e.CollationName));
    }

    /// <summary>
    /// Looks up the probed outcome for a column of <paramref name="columnCategory"/> compared
    /// against <paramref name="otherCategory"/>. For a string-family pair, pass the column's
    /// effective collation name; a probe recorded for a different collation is not reused for
    /// another - collation is comparison-relevant, not incidental. Returns null if this exact
    /// cell was never probed.
    /// </summary>
    public TypePairOutcome? TryGetOutcome(SqlTypeCategory columnCategory, SqlTypeCategory otherCategory, string? collationName = null) =>
        _byKey.TryGetValue((columnCategory, otherCategory, collationName), out var outcome) ? outcome : null;

    /// <summary>
    /// For a string-family column whose own collation is unresolved: some category pairs
    /// (e.g. nvarchar column vs varchar value) never convert the column regardless of which
    /// collation is in play - that's a precedence-direction fact, not a collation-dependent
    /// one, verified empirically by every probed collation variant of the pair agreeing. This
    /// is NOT a guess - it only returns a result when every collation this matrix ever probed
    /// for the pair reached the identical outcome; a pair where collation genuinely changes the
    /// answer (varchar column vs nvarchar value - ScanForced under SQL_*, RangeSeek under
    /// Windows) returns null here exactly as it should, forcing the caller to fall back to
    /// UNKNOWN rather than pick one collation's answer arbitrarily.
    /// </summary>
    public TypePairOutcome? TryGetOutcomeAgreeingAcrossCollations(SqlTypeCategory columnCategory, SqlTypeCategory otherCategory)
    {
        var variants = Entries.Where(e => e.ColumnCategory == columnCategory && e.OtherCategory == otherCategory && e.CollationName is not null).ToList();
        if (variants.Count == 0)
        {
            return null;
        }

        var first = variants[0];
        var allAgree = variants.All(v => v.CompileFailed == first.CompileFailed
            && v.ColumnConverts == first.ColumnConverts
            && v.DynamicRangeSeekAvailable == first.DynamicRangeSeekAvailable);

        return allAgree ? first with { CollationName = null } : null;
    }

    private static TypePairMatrix LoadEmbedded()
    {
        var assembly = typeof(TypePairMatrix).Assembly;
        var resourceName = $"{assembly.GetName().Name}.Rules.TypePairMatrix.json";
        using var stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{resourceName}' not found - the matrix data is missing from the build.");

        var document = JsonSerializer.Deserialize<MatrixDocument>(stream, JsonOptions)
            ?? throw new InvalidOperationException("TypePairMatrix.json deserialized to null.");

        var entries = document.Entries.Select(e => new TypePairOutcome(
            Enum.Parse<SqlTypeCategory>(e.ColumnCategory),
            Enum.Parse<SqlTypeCategory>(e.OtherCategory),
            e.CollationName,
            e.ColumnConverts,
            e.CompileFailed,
            e.DynamicRangeSeekAvailable)).ToList();

        return new TypePairMatrix(document.ServerVersion, document.ProbedAtUtc, entries);
    }

    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };

    private sealed record MatrixDocument(
        [property: JsonPropertyName("ServerVersion")] string ServerVersion,
        [property: JsonPropertyName("ProbedAtUtc")] string ProbedAtUtc,
        [property: JsonPropertyName("Notes")] string Notes,
        [property: JsonPropertyName("Entries")] IReadOnlyList<MatrixEntryDocument> Entries);

    private sealed record MatrixEntryDocument(
        string ColumnCategory,
        string OtherCategory,
        string? CollationName,
        bool ColumnConverts,
        bool CompileFailed,
        bool DynamicRangeSeekAvailable);
}
